/* Shared operator views. Read-only projections of the current location. */
(()=>{'use strict';
const $=id=>document.getElementById(id),E=escapeHtml;
const money=n=>Number.isFinite(n)?new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n):'—';
let state=null,life=null;
const go=(route,label)=>`<button type="button" data-design-route="${route}">${E(label)}</button>`;
document.addEventListener('click',e=>{const b=e.target.closest('[data-design-route]');if(b)window.switchTab(b.dataset.designRoute);});
function slot(route){const p=$('page-'+route);if(!p)return null;let el=p.querySelector('.design-overview');if(!el){el=document.createElement('section');el.className='design-overview';p.querySelector('.main-hdr')?.after(el);}return el;}
function months(){const b=state?.books;if(b?.length!==1)return [];const m=b[0].snapshot?.monthly;if(!m)return [];const names=['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'],now=new Date(),cutoff=now.getUTCFullYear()*12+now.getUTCMonth();return (m.months||[]).map((label,i)=>{const hit=/^(\w{3}) (\d{4})$/.exec(label);if(!hit||names.indexOf(hit[1])<0)return null;const key=Number(hit[2])*12+names.indexOf(hit[1]),revenue=Number(m.income?.[i]),net=Number(m.net_income?.[i]);if(key>=cutoff||m.income?.[i]==null||m.net_income?.[i]==null||!Number.isFinite(revenue)||!Number.isFinite(net))return null;return {label,key,revenue,net};}).filter(Boolean).sort((a,b)=>a.key-b.key).slice(-6);}
function trend(points,key,title,color){const values=points.map(p=>p[key]),min=Math.min(0,...values),max=Math.max(1,...values),zero=150-(0-min)/(max-min)*110,y=v=>150-(v-min)/(max-min)*110,x=i=>40+i*(620/Math.max(1,points.length-1));return `<div class="design-chart"><h3>${E(title)}</h3><svg viewBox="0 0 710 210" role="img" aria-label="${E(title)}; exact values in the table below"><line x1="30" x2="680" y1="${zero}" y2="${zero}" stroke="#dce2ec"/><polyline points="${values.map((v,i)=>x(i)+','+y(v)).join(' ')}" fill="none" stroke="${color}" stroke-width="3" stroke-linejoin="round"/>${points.map((p,i)=>`<circle cx="${x(i)}" cy="${y(p[key])}" r="4" fill="${color}"><title>${E(p.label)}: ${money(p[key])}</title></circle><text x="${x(i)}" y="190" text-anchor="middle">${E(p.label.split(' ')[0])}</text>`).join('')}</svg></div>`;}
function operating(){const p=months();if(!p.length)return;const last=p.at(-1),prev=p.at(-2),change=prev&&prev.revenue>0?(last.revenue/prev.revenue-1)*100:null;const report=slot('books');report.innerHTML=`<header class="design-heading"><div><h2>Your operating picture</h2><p>${E(last.label)} · latest reported month</p></div>${go('plan','Budget & forecast')}</header><div class="design-metrics"><div><span>Revenue</span><strong>${money(last.revenue)}</strong><small>${change===null?'Prior comparison unavailable':Math.abs(change).toFixed(1)+'% '+(change>=0?'higher':'lower')+' than '+E(prev.label)}</small></div><div><span>Net income</span><strong>${money(last.net)}</strong><small>${last.revenue>0?(last.net/last.revenue*100).toFixed(1)+'% of sales':'Margin unavailable'}</small></div><div><span>Net costs</span><strong>${money(last.revenue-last.net)}</strong><small>Revenue less net income</small></div></div>${trend(p,'revenue','Sales over time','#4768b4')}<div class="design-table"><table><caption>Monthly results · QuickBooks</caption><thead><tr><th>Month</th><th>Sales</th><th>Net income</th><th>Net margin</th></tr></thead><tbody>${p.map(r=>`<tr><th>${E(r.label)}</th><td>${money(r.revenue)}</td><td>${money(r.net)}</td><td>${r.revenue>0?(r.net/r.revenue*100).toFixed(1)+'%':'—'}</td></tr>`).join('')}</tbody></table></div><p class="design-source">Use the report controls below for account detail. Elapsed months do not establish complete or accountant-reviewed books.</p>`;
const home=slot('dashboard');home.innerHTML=`<div class="design-heading"><div><h2>Your latest month</h2><p>${E(last.label)} · reported books</p></div>${go('books','Explore performance')}</div><p class="design-insight">${money(last.revenue)} in sales${change===null?'':', '+Math.abs(change).toFixed(1)+'% '+(change>=0?'up':'down')+' from the prior reported month'}. ${last.net>=0?'Net income was ':'Net loss was '}${money(Math.abs(last.net))}.</p>`;$('financial-home')?.after(home);
}
function serviceSearch(){const host=$('page-services')?.querySelector('.section-launchpad');if(!host||host.querySelector('.design-search'))return;const wrap=document.createElement('div');wrap.className='design-search';wrap.innerHTML='<label>Find a service<input type="search" placeholder="Payroll, insurance, bookkeeping…" aria-label="Find a service"></label><p role="status" class="design-source">9 services · arranged through CoverPanda</p>';host.querySelector('.launch-grid')?.before(wrap);wrap.querySelector('input').oninput=e=>{const q=e.target.value.trim().toLowerCase();let count=0;host.querySelectorAll('[data-service-choice]').forEach(c=>{const show=c.textContent.toLowerCase().includes(q);c.hidden=!show;if(show)count++;});wrap.querySelector('[role=status]').textContent=count?count+' matching service'+(count===1?'':'s'):'No matches. Try payroll, tax or insurance.';};}
function evidence(){if(!state||state.wallet.access_role)return;const records=state.records||[],docs=records.filter(r=>r.kind==='document'),profile=life?.records?.find(r=>r.kind==='readiness_profile')?.data;const items=profile&&window.FranReadiness?FranReadiness.plan(profile,life.records,state).filter(r=>r.audience!=='private'):[];const host=slot('documents');const current=items.filter(r=>r.status==='current').length;host.innerHTML=`<header class="design-heading"><div><h2>Your location’s data room</h2><p>${E(state.wallet.name)} · private until shared</p></div>${go('dataroom','Review sharing')}</header><div class="design-metrics"><div><span>Saved originals</span><strong>${docs.length}</strong><small>Files belonging to this location</small></div><div><span>Evidence reviewed</span><strong>${items.length?current+' / '+items.length:life?'Not assessed':'Loading…'}</strong><small>${items.length?'Current items in your readiness plan':'Set your readiness goal to assess coverage'}</small></div><div><span>Shared snapshots</span><strong>${(state.rooms||[]).length}</strong><small>Review expiration and recipients</small></div></div><div class="design-evidence">${items.length?items.filter(r=>r.audience!=='private').map(r=>`<button type="button" data-design-evidence="${E(r.id)}"><span><strong>${E(r.title)}</strong><small>${E(r.group)}</small></span><span class="design-status status-${r.status}">${E(({current:'Reviewed',suggested:'Review match',missing:'Needed',refresh:'Refresh due',exception:'Exception recorded',external:'Prepared externally'})[r.status]||'Review')}</span></button>`).join(''):!life?'<p>Loading your saved readiness plan…</p>':'<p>Choose your financing or exit goal to generate the evidence plan.</p>'+go('readiness','Set readiness goal')}</div><p class="design-source">Coverage tracks reviewed evidence, not lender approval. Your saved files and Drive sources are below.</p>`;}
function insurance(){const host=slot('insurance'),docs=(state.records||[]).filter(r=>r.kind==='document'&&/insurance|policy|certificate|\bcoi\b/i.test(r.data.name||''));host.innerHTML=`<header class="design-heading"><div><h2>Your protection, in one place</h2><p>Coverage records and a clear path to help.</p></div>${go('services','Speak with CoverPanda')}</header><div class="design-insurance"><div><h3>Policy documents</h3>${docs.length?docs.map(d=>`<div class="design-document"><strong>${E(d.data.name)}</strong><span>Saved · coverage not independently verified</span></div>`).join(''):'<p>No policy document identified by filename yet. Add a policy or certificate to begin.</p>'}${go('documents','Open document vault')}</div><div><h3>What do you need?</h3>${go('services','Request a coverage review')}${go('services','Request a certificate')}${go('entity','Review renewal reminders')}<p class="design-source">Your provider confirms policy terms, certificates and any changes to coverage.</p></div></div>`;}
window.addEventListener('fran:location',e=>{const next=e.detail;if(next?.wallet.id!==state?.wallet.id)life=null;state=next;document.querySelectorAll('.design-overview').forEach(el=>el.remove());document.body.classList.toggle('design-owner',!!state&&!state.wallet.access_role);if(!state||state.wallet.access_role)return;insurance();serviceSearch();});
window.addEventListener('fran:readiness',e=>{if(e.detail.location?.wallet.id!==state?.wallet.id)return;life=e.detail.life;});
function payroll(){
 const reports=months(), rows=(state.records||[]).filter(r=>r.kind==='payroll'), totals=new Map();
 for(const r of rows){const d=r.data||{},match=/^(\d{4})-(\d{2})-\d{2}$/.exec(d.date||'');if(!match)continue;const key=Number(match[1])*12+Number(match[2])-1;const fields=[d.gross,d.taxes,d.benefits];if(fields.some(v=>v!=null&&!Number.isFinite(Number(v))))continue;totals.set(key,(totals.get(key)||0)+fields.reduce((sum,v)=>sum+Number(v||0),0));}
 const points=reports.filter(r=>totals.has(r.key)).map(r=>({...r,cost:totals.get(r.key),ratio:r.revenue>0?totals.get(r.key)/r.revenue*100:null}));if(!points.length)return;
 const last=points.at(-1),prev=points.at(-2),delta=prev&&last.key===prev.key+1&&last.ratio!==null&&prev.ratio!==null?last.ratio-prev.ratio:null;
 slot('payroll').innerHTML=`<header class="design-heading"><div><h2>Understand your labor spend</h2><p>${E(last.label)} · imported payroll and reported sales</p></div>${go('books','Compare with sales')}</header><div class="design-metrics"><div><span>Employer labor cost</span><strong>${money(last.cost)}</strong><small>Gross wages + employer taxes + benefits</small></div><div><span>Share of sales</span><strong>${last.ratio===null?'—':last.ratio.toFixed(1)+'%'}</strong><small>${delta===null?'Monthly comparison unavailable':Math.abs(delta).toFixed(1)+' percentage points '+(delta<=0?'lower':'higher')+' than '+E(prev.label)}</small></div><div><span>One point of sales</span><strong>${money(last.revenue*.01)}</strong><small>Monthly cost equivalent of a 1-point change</small></div></div><div class="design-table"><table><caption>Labor against sales</caption><thead><tr><th>Month</th><th>Labor cost</th><th>Sales</th><th>Labor / sales</th></tr></thead><tbody>${points.map(r=>`<tr><th>${E(r.label)}</th><td>${money(r.cost)}</td><td>${money(r.revenue)}</td><td>${r.ratio===null?'—':r.ratio.toFixed(1)+'%'}</td></tr>`).join('')}</tbody></table></div><p class="design-source">Based on imported pay dates. Missing pay runs can understate cost; sales use the books’ reporting basis. Position-level analysis needs a report containing roles. Payroll records and import controls remain below.</p>`;
}

function laborQuestions(){
 if(!state||state.wallet.access_role)return;const host=slot('payroll');host.querySelector('.labor-questions')?.remove();
 const panel=document.createElement('section');panel.className='labor-questions';panel.innerHTML='<h3>Ask Fran about your labor</h3><p>Answers from this location’s saved payroll and books.</p><div class="rb-segment"><button type="button" data-labor-question="trend">How is labor changing?</button><button type="button" data-labor-question="books">Compare payroll with books</button><button type="button" data-labor-question="coverage">What is missing?</button></div><div class="labor-answer" role="status"></div>';host.querySelector('.design-table')?.before(panel);if(!panel.isConnected)host.append(panel);
 panel.onclick=e=>{const b=e.target.closest('[data-labor-question]');if(!b)return;const records=(state.records||[]).filter(r=>r.kind==='payroll'),months=new Map();for(const r of records){const d=r.data,k=d.date?.slice(0,7);if(!k||[d.gross,d.taxes,d.benefits].some(v=>v==null||!Number.isFinite(Number(v))))continue;months.set(k,(months.get(k)||0)+Number(d.gross)+Number(d.taxes)+Number(d.benefits));}const rows=[...months].filter(([k])=>k<new Date().toISOString().slice(0,7)).sort(([a],[b])=>a.localeCompare(b)),last=rows.at(-1),prev=rows.at(-2);let answer;
 if(b.dataset.laborQuestion==='trend')answer=last?'Imported payroll for '+last[0]+' totals '+money(last[1])+'. '+(prev?'Compared with '+prev[0]+', that is '+money(Math.abs(last[1]-prev[1]))+' '+(last[1]>=prev[1]?'higher':'lower')+'. ':'')+'Pay dates and missing runs can change this comparison; this is not a worked-hours productivity measure.':'Import payroll reports to compare monthly costs.';
 if(b.dataset.laborQuestion==='coverage')answer='Imported payroll provides pay-date costs. QuickBooks provides posted accounting expenses; do not add the two together. Job titles, complete run coverage, and any missing benefit costs still need confirmation. A role-level export is required for position analysis.';
 if(b.dataset.laborQuestion==='books'){const book=state.books?.length===1?state.books[0]:null,detail=book?.snapshot?.pl_detail;const matched=(detail?.rows||[]).filter(r=>r.kind==='account'&&/wages|salaries|payroll tax|cost of labor|employer benefit/i.test(r.name||''));const date=last?.[0],label=date?new Date(date+'-15T12:00:00Z').toLocaleDateString('en-US',{month:'short',year:'numeric',timeZone:'UTC'}):null,ix=detail?.months?.indexOf(label)??-1;const complete=ix>=0&&matched.length&&matched.every(r=>r.values?.[ix]!=null&&Number.isFinite(Number(r.values[ix])));answer=complete?'For '+label+', matched QuickBooks labor accounts total '+money(matched.reduce((n,r)=>n+Number(r.values[ix]),0))+'; imported payroll totals '+money(last[1])+'. Matched accounts: '+matched.map(r=>r.name).join(', ')+'. Account-name matching is provisional. Accruals, tips and posting dates can explain differences; these sources are not added together.':'Detailed QuickBooks labor accounts are unavailable for the latest imported payroll month. Open Accounting to refresh the detailed reports. Payroll imports remain available independently.';}
 panel.querySelector('.labor-answer').textContent=answer;
 };
}

document.addEventListener('click',e=>{if(e.target.closest('#page-insurance [data-design-route="services"]'))document.querySelector('[data-service-choice="insurance"]')?.click();});
document.addEventListener('click',e=>{const b=e.target.closest('[data-design-evidence]');if(b)window.dispatchEvent(new CustomEvent('fran:open-evidence',{detail:{id:b.dataset.designEvidence}}));});
// Keep navigation meaningful to browsers and assistive technology.
const destinations={dashboard:'Home',banking:'Finance',books:'Accounting',payroll:'Payroll',company:'Company',entity:'Compliance',insurance:'Insurance',documents:'Data room',readiness:'Readiness',dataroom:'Sharing',value:'Valuation',plan:'Budget & forecast',services:'Support',marketplace:'Marketplace',community:'Community',settings:'Settings'};
let replaying=false,routeInitialized=false;
const previousSwitch=window.switchTab;
window.switchTab=function(route,...args){
 previousSwitch(route,...args);
 const periodControl=$('shared-reporting-period');if(periodControl){periodControl.hidden=!state||!!state.wallet.access_role||!['dashboard'].includes(route);if(!periodControl.hidden){if(route==='dashboard')$('financial-home')?.querySelector('.fh-top')?.after(periodControl);else $('page-'+route)?.querySelector('.main-hdr')?.after(periodControl);}}
 if(!state||state.wallet.access_role||!destinations[route])return;
 const heading=$('page-'+route)?.querySelector('h1');
 if(heading){heading.tabIndex=-1;heading.focus({preventScroll:true});}
 document.title=destinations[route]+' · FranWallet';
 if(!replaying){const url=new URL(location.href);if(url.searchParams.get('view')!==route){url.searchParams.set('view',route);history.pushState(null,'',url);}}
};
window.addEventListener('popstate',()=>{if(!state||state.wallet.access_role)return;const route=new URL(location.href).searchParams.get('view')||'dashboard';if(destinations[route]){replaying=true;window.switchTab(route);replaying=false;}});
function checkin(){
 if(!state||state.wallet.access_role)return;
 const home=slot('dashboard'),reported=months(),latest=reported.at(-1),bankDates=(state.banks||[]).map(b=>b.last_synced?.slice(0,10)),payDates=(state.records||[]).filter(r=>r.kind==='payroll').map(r=>r.data.date).filter(Boolean).sort();
 const bankDate=bankDates.length&&bankDates.every(Boolean)?bankDates.sort()[0]:null;
 const stale=bankDate&&Date.now()-Date.parse(bankDate)>7*864e5;
 const action=!latest?['books','Connect or review your books','Add reported sales and profit to make this snapshot useful.']:stale?['banking','Review your bank snapshot','Your oldest linked-bank snapshot is more than seven days old.']:latest.net<0?['books','Review your latest month’s costs',money(Math.abs(latest.net))+' net loss reported for '+latest.label+'. Open the accounts behind the result.']:['plan','Review your next month’s plan','Use reported results as a starting point, then check the cash timing.'];
 home.innerHTML=`<div class="design-heading"><div><h2>${E(action[1])}</h2><p>${E(action[2])}</p></div>${go(action[0],'Open '+destinations[action[0]])}</div><div class="journey-sources" aria-label="Data coverage"><button data-design-route="banking"><span>Bank snapshot</span><strong>${E(bankDate||'Date unavailable')}</strong><small>${stale?'Review freshness':bankDate?'Saved balance, not live cash':'Connect or check source dates'}</small></button><button data-design-route="books"><span>Reported books</span><strong>${E(latest?.label||'Not available')}</strong><small>Elapsed month · completeness not verified</small></button><button data-design-route="payroll"><span>Latest imported pay date</span><strong>${E(payDates.at(-1)||'No payroll imported')}</strong><small>Run coverage requires review</small></button></div>`;
 $('financial-home')?.after(home);
 const intro=$('financial-home')?.querySelector('.launch-instruction');if(intro){intro.className='launch-instruction journey-priority';intro.innerHTML='<div><strong>'+E(action[1])+'</strong><p>'+E(action[2])+'</p></div>'+go(action[0],'Review');}
 const sourceHeading=home.querySelector('h2');if(sourceHeading)sourceHeading.textContent='Know what your snapshot covers';
 const sourceCopy=home.querySelector('.design-heading p');if(sourceCopy)sourceCopy.textContent='Check the source dates before making a decision.';
 const cashNote=$('financial-home')?.querySelector('.fh-tile small');if(cashNote)cashNote.textContent=bankDate?'Bank snapshot · '+bankDate:'Bank snapshot date unavailable';
 const heading=$('page-books')?.querySelector('.main-hdr h1');if(heading)heading.textContent='Accounting';
}
window.addEventListener('fran:location',()=>{
 checkin();
 if(state&&!state.wallet.access_role&&!routeInitialized){routeInitialized=true;const url=new URL(location.href),route=url.searchParams.get('view')||'dashboard';if(destinations[route]){url.searchParams.set('view',route);history.replaceState(null,'',url);replaying=true;window.switchTab(route);replaying=false;}}
});
function periodSummary(p){
 if(!state||state.wallet.access_role||p.wallet!==state.wallet.id)return;
 const revenue=p.current?.revenue??null,net=p.current?.net??null,label=p.start+' – '+p.end,percent=(a,b)=>a!==null&&b>0&&!p.timingRisk?(a/b*100).toFixed(1)+'%':'—';
 const homeTiles=$('financial-home')?.querySelectorAll('.fh-tile');
 if(homeTiles?.length===4){homeTiles[2].querySelector('strong').textContent=money(revenue);homeTiles[2].querySelector('small').textContent=label;homeTiles[3].querySelector('strong').textContent=money(net);homeTiles[3].querySelector('small').textContent=percent(net,revenue)+' net margin · '+label;}
 const report=slot('books');
 if(!report.querySelector('.design-metrics'))report.innerHTML='<header class="design-heading"><div><h2>Your operating picture</h2><p></p></div></header><div class="design-metrics"><div></div><div></div><div></div></div>';
 report.querySelector('.design-heading p').textContent=label+' · '+(p.current?.basis||'Reported books');
 const prior=p.previous?.revenue,change=prior>0&&revenue!==null?(revenue/prior-1)*100:null;
 const metrics=[['Revenue',money(revenue),change===null?'Comparison unavailable':Math.abs(change).toFixed(1)+'% '+(change>=0?'higher':'lower')+' than comparison period'],['Net income',money(net),p.timingRisk?'Review revenue timing':percent(net,revenue)+' of sales'],['Net costs',money(revenue!==null&&net!==null?revenue-net:null),'Revenue less net income']];
 [...report.querySelector('.design-metrics').children].forEach((el,i)=>el.innerHTML='<span>'+E(metrics[i][0])+'</span><strong>'+E(metrics[i][1])+'</strong><small>'+E(metrics[i][2])+'</small>');
 const pay=slot('payroll');
 if(!pay.querySelector('.design-metrics'))pay.innerHTML='<header class="design-heading"><div><h2>Understand your labor spend</h2><p></p></div></header><div class="design-metrics"><div></div><div></div><div></div></div>';
 pay.querySelector('.design-heading p').textContent=label+' · selected reporting period';
 const labor=p.payrollCovered?p.labor:null,pm=[['Imported employer cost',money(labor),p.excludeTips?'Excluding paycheck tips':'Including paycheck tips'],['Share of sales',percent(labor,revenue),p.timingRisk?'Review revenue timing':p.payrollCovered?'Pay-date cost / reported sales':'Import coverage does not support this range'],['One point of sales',money(revenue!==null?revenue*.01:null),'Monthly only when a full month is selected']];
 [...pay.querySelector('.design-metrics').children].forEach((el,i)=>el.innerHTML='<span>'+E(pm[i][0])+'</span><strong>'+E(pm[i][1])+'</strong><small>'+E(pm[i][2])+'</small>');
 let coverage=pay.querySelector('.period-coverage-note');if(!coverage){coverage=document.createElement('p');coverage.className='period-coverage-note design-source';pay.querySelector('.design-metrics').after(coverage);}coverage.textContent=p.payrollCovered?'Imported report dates support the selection. This does not independently verify that every payroll run is present.':'No exact payroll total for these dates. Review imported report coverage or choose a supported period.';
 let toggle=pay.querySelector('[data-payroll-detail]');if(!toggle){toggle=document.createElement('button');toggle.type='button';toggle.dataset.payrollDetail='';toggle.textContent='Review imported payroll detail';toggle.setAttribute('aria-expanded','false');pay.append(toggle);}
 for(const table of [report.querySelector('caption'),pay.querySelector('caption')])if(table&&!table.textContent.startsWith('Historical'))table.textContent='Historical months · '+table.textContent;
}

window.addEventListener('fran:location',()=>{if(state&&!state.wallet.access_role&&(state.records||[]).some(r=>r.kind==='service')){const gallery=$('page-services')?.querySelector('.section-launchpad');if(gallery)$('fw-services')?.after(gallery);}});
document.addEventListener('click',e=>{const b=e.target.closest('[data-payroll-detail]');if(!b)return;const panel=document.querySelector('.labor-studio');if(panel){const open=panel.dataset.expanded!=='true';panel.dataset.expanded=String(open);b.setAttribute('aria-expanded',String(open));b.textContent=open?'Hide imported payroll detail':'Review imported payroll detail';if(open)panel.scrollIntoView({block:'start'});}});
})();
