/* Landing: a live, readable demo of the first session, and what to expect after it.
   Built from the same interface owners use (Set up with Fran, the Wallet card, "Here's what I found").
   Every figure is an illustrative example and labeled so. Autoplays, pauses on hover/focus, steps are
   clickable, and reduced-motion visitors get a still, step-through version. */
(()=>{'use strict'
const $=s=>document.querySelector(s),reduce=matchMedia('(prefers-reduced-motion: reduce)').matches
const track=(n,p)=>{try{window.posthog?.capture(n,p)}catch(_){}}
const I={company:'<path d="M4 21V5l8-3 8 3v16"/><path d="M9 21v-5h6v5M8 8h.01M12 8h.01M16 8h.01M8 12h.01M12 12h.01M16 12h.01"/>',lease:'<path d="M3 11 12 4l9 7"/><path d="M5 10v10h14V10"/><path d="M10 20v-5h4v5"/>',bank:'<path d="M3 9 12 4l9 5"/><path d="M5 10v8M9.5 10v8M14.5 10v8M19 10v8M3 20h18"/>',books:'<path d="M4 19V5a2 2 0 0 1 2-2h12v16H6a2 2 0 0 0-2 2Zm0 0a2 2 0 0 0 2 2h12"/><path d="M8 8h6M8 12h6"/>',payroll:'<circle cx="9" cy="8" r="3"/><path d="M3 20c.7-3.4 3-5 6-5s5.3 1.6 6 5"/><path d="M16 4.5a3 3 0 0 1 0 6M18 15c1.8.6 2.8 2.2 3 5"/>',insurance:'<path d="M12 3 5 6v5c0 4.4 2.9 8.3 7 10 4.1-1.7 7-5.6 7-10V6l-7-3Z"/>',check:'<path d="m5 12 4 4 10-10"/>',file:'<path d="M14 3H7a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V8l-5-5Z"/><path d="M14 3v5h5"/>',people:'<circle cx="9" cy="8" r="3"/><path d="M3 20c.7-3.4 3-5 6-5s5.3 1.6 6 5M17 11v6M14 14h6"/>',link:'<path d="M10 14a4 4 0 0 0 5.7 0l3-3a4 4 0 0 0-5.7-5.7l-1 1"/><path d="M14 10a4 4 0 0 0-5.7 0l-3 3a4 4 0 0 0 5.7 5.7l1-1"/>',spark:'<path d="M12 3v4M12 17v4M3 12h4M17 12h4M6 6l2.5 2.5M15.5 15.5 18 18M18 6l-2.5 2.5M8.5 15.5 6 18"/>'}
const svg=n=>'<svg viewBox="0 0 24 24" aria-hidden="true" focusable="false">'+(I[n]||'')+'</svg>'
const PARTS=[['company','Company'],['lease','Lease'],['bank','Bank'],['books','Books'],['payroll','Payroll'],['insurance','Insurance']]
/* What the Wallet card shows after each scene. */
const CARD=[
 {name:'',sub:'Name your location to begin',n:0,st:{}},
 {name:'Crumbl · Eastlake',sub:'Crumbl · Denver, CO',n:3,st:{company:'saved',lease:'reading',insurance:'saved'}},
 {name:'Crumbl · Eastlake',sub:'Crumbl · Denver, CO',n:3,st:{company:'saved',lease:'saved',insurance:'saved'}},
 {name:'Crumbl · Eastlake',sub:'Crumbl · Denver, CO',n:3,st:{company:'saved',lease:'saved',insurance:'saved',books:'invited',payroll:'invited'}},
 {name:'Crumbl · Eastlake',sub:'Crumbl · Denver, CO',n:4,st:{company:'saved',lease:'saved',insurance:'saved',books:'saved',payroll:'invited',bank:'next'}}]
const LABEL={saved:'Saved',reading:'Reading…',invited:'Invite sent',next:'Up next','':'Not started'}
const STEPS=[
 {k:'name',t:'Name it',d:'Tell Fran about the location.'},
 {k:'bring',t:'Bring what you have',d:'Drop in a folder. Fran sorts it.'},
 {k:'found',t:'Here’s what I found',d:'Check the details, then save.'},
 {k:'invite',t:'Invite who helps',d:'Your accountant connects the books.'},
 {k:'plan',t:'See it working',d:'Your plan, your next step.'}]
const msg=(html,cls='')=>'<div class="ld-msg '+cls+'"><span class="ld-av" aria-hidden="true">F.</span><p>'+html+'</p></div>'
const you=t=>'<div class="ld-you">'+t+'</div>'
function scene(i){switch(i){
 case 0:return msg('<strong>Welcome to your Wallet.</strong> I’ll bring your company, lease, bank, books, payroll and insurance into one place.')+msg('First, what do you call this location?')+'<div class="ld-input"><span class="ld-typed" data-type="Crumbl · Eastlake"></span><i class="ld-caret"></i><b>Continue →</b></div><div class="ld-later" style="--d:2.4s">'+msg('Where is Crumbl · Eastlake today?')+'<div class="ld-chips"><span>Getting ready to open</span><span class="on">Open and operating</span></div></div>'
 case 1:return msg('Drop in what you already have. I’ll sort it and pull out the details.')+'<ul class="ld-inbox">'+[['lease','Eastlake Lease.pdf','Lease · details found','found'],['bank','SBA Note.pdf','Loan · details found','found'],['company','Operating Agreement.pdf','Company · details found','found'],['insurance','COI 2026.pdf','Insurance · saved',''],['file','GC Contract.pdf','Build-out contract · saved','']].map(([ic,n,l,s],j)=>'<li class="'+s+'" style="--d:'+(j*.35)+'s"><span class="ld-ic">'+svg(ic)+'</span><span class="ld-fn">'+n+'</span><em>'+l+'</em></li>').join('')+'</ul>'
 case 2:return '<div class="ld-review"><header><span class="ld-ic dark">'+svg('lease')+'</span><div><small>LEASE · Eastlake Lease.pdf</small><h4>Here’s what I found</h4></div><span class="ld-count">11 found</span></header><div class="ld-fields">'+[['Landlord','Thornton Retail Partners, LLC','“…by and between Thornton Retail Partners, LLC (“Landlord”)…”'],['Base rent','$6,500 / month','“Tenant shall pay Base Rent of $6,500.00 per month.”'],['CAM','$1,150 / month','“…CAM charges, estimated at $1,150.00 per month.”'],['Expires','Feb 28, 2034','Calculated from a March 1, 2024 start and a 10-year term']].map(([l,v,e],j)=>'<div class="ld-field" style="--d:'+(j*.3)+'s"><span>'+l+' <i>✓</i></span><strong>'+v+'</strong><small>'+e+'</small></div>').join('')+'</div><footer><b class="ld-save">Save to Wallet</b><span>Nothing is saved until you press Save.</span></footer></div><div class="ld-later" style="--d:3.2s">'+msg('<strong>✓ Saved to your Wallet.</strong> Thornton Retail Partners · $6,500/mo through Feb 28, 2034.')+'</div>'
 case 3:return msg('Who already helps you run Crumbl · Eastlake? They’ll connect their part for you.')+'<div class="ld-vendors"><div class="ld-vendor on"><i>✓</i><span><strong>My accountant</strong><small>Connects QuickBooks</small></span><em>Free</em></div><div class="ld-vendor on"><i>✓</i><span><strong>My payroll provider</strong><small>Adds payroll reports</small></span><em>Free</em></div></div><div class="ld-link"><span class="ld-ic">'+svg('link')+'</span><span>Private invite for <strong>cpa@eastlakecpa.com</strong> · this location only</span><b>Copy link</b></div>'
 case 4:return msg('<strong>✓ Your plan is saved.</strong> Built from your lease, your loan and your accountant’s books.')+'<div class="ld-kpis">'+[['Year 1 revenue','$1.14M'],['EBITDA','$148K','13% margin'],['Debt coverage','3.0×','Covers payments'],['Next up','Connect bank','2 minutes with Plaid']].map(([l,v,s],j)=>'<div style="--d:'+(j*.2)+'s"><span>'+l+'</span><strong>'+v+'</strong>'+(s?'<small>'+s+'</small>':'')+'</div>').join('')+'</div>'+spark()+'<div class="ld-sources"><span>✓ Occupancy $7,650/mo <small>from your lease</small></span><span>✓ Debt payments $4,109/mo <small>from your SBA note</small></span></div>'}}
/* Plan vs actual, last six months: bars are actual, the dashed line is the plan. */
function spark(){const plan=[88,90,92,94,95,97],act=[84,92,90,97,99,101],W=300,H=64,x=i=>14+i*48,y=v=>H-6-(v-78)/(104-78)*(H-14)
 return '<div class="ld-spark" style="--d:.9s"><span>Plan vs. actual · last 6 months</span><svg viewBox="0 0 '+W+' '+H+'" role="img" aria-label="Actual revenue at or above plan in four of the last six months">'+act.map((v,i)=>'<rect x="'+x(i)+'" y="'+y(v).toFixed(1)+'" width="22" height="'+(H-6-y(v)).toFixed(1)+'" rx="3" class="'+(v>=plan[i]?'up':'dn')+'"/>').join('')+'<path d="'+plan.map((v,i)=>(i?'L':'M')+(x(i)+11)+' '+y(v).toFixed(1)).join(' ')+'" class="pl"/></svg></div>'}
function card(i){const c=CARD[i];return '<div class="ld-card'+(c.name?' named':'')+'"><div class="ld-card-head"><span>FRAN WALLET</span><b>'+c.n+' of 6</b></div><h3>'+(c.name||'Your location')+'</h3><p>'+c.sub+'</p><div class="ld-meter"><i style="width:'+Math.round(c.n/6*100)+'%"></i></div><ol>'+PARTS.map(([k,l])=>{const s=c.st[k]||'';return '<li data-s="'+s+'"><span class="ld-slot">'+svg(s==='saved'?'check':k)+'</span><span>'+l+'</span><em>'+LABEL[s]+'</em></li>'}).join('')+'</ol></div><div class="ld-unlocks"><small>WHAT IT UNLOCKS</small><div>'+[['Monthly numbers',i>=4],['Renewal calendar',i>=2],['Debt schedule',i>=2],['Lender summary',i>=4]].map(([t,on])=>'<span class="'+(on?'on':'')+'">'+(on?'✓ ':'')+t+'</span>').join('')+'</div></div>'}
function stage(){return '<div class="ld-demo" role="region" aria-roledescription="carousel" aria-label="What your first session looks like"><div class="ld-window"><div class="ld-chrome"><span class="ld-dots" aria-hidden="true"><i></i><i></i><i></i></span><span class="ld-title"><b>F.</b> Set up with Fran</span><button type="button" class="ld-pause" aria-label="Pause the demo">Pause</button></div><div class="ld-body"><div class="ld-chat" aria-live="polite"></div><aside class="ld-wallet" aria-label="The Wallet, as it fills in"></aside></div></div><ol class="ld-steps" role="tablist">'+STEPS.map((s,i)=>'<li role="presentation"><button type="button" role="tab" data-step="'+i+'" aria-selected="false"><span class="ld-n">'+(i+1)+'</span><span class="ld-st"><strong>'+s.t+'</strong><small>'+s.d+'</small></span><i class="ld-prog" aria-hidden="true"></i></button></li>').join('')+'</ol><p class="ld-note">Illustrative example of a first session. Your numbers come from your own records.</p></div>'}
function mountHero(){const target=$('.land-hero .product-shot')||$('.wallet-command-visual');if(!target||$('.ld-demo'))return null;const wrap=document.createElement('div');wrap.innerHTML=stage();const demo=wrap.firstElementChild;target.replaceWith(demo);return demo}
function run(demo){const chat=demo.querySelector('.ld-chat'),wallet=demo.querySelector('.ld-wallet'),tabs=[...demo.querySelectorAll('[data-step]')],pauseBtn=demo.querySelector('.ld-pause');let i=0,timer=null,typer=null,paused=reduce,hover=false,seen=new Set()
 const DUR=[5200,5600,6200,5400,6400]
 const show=(n,user)=>{i=n;clearTimeout(timer);clearInterval(typer);chat.innerHTML='<div class="ld-scene">'+scene(n)+'</div>';wallet.innerHTML=card(n===0?0:n);tabs.forEach((t,j)=>{t.setAttribute('aria-selected',j===n);t.tabIndex=j===n?0:-1;t.classList.toggle('done',j<n);const p=t.querySelector('.ld-prog');p.style.animation='none';void p.offsetWidth;p.style.animation=''})
  demo.dataset.scene=n;if(!seen.has(n)){seen.add(n);track('landing_demo_scene',{scene:STEPS[n].k,user:!!user})}
  const typed=chat.querySelector('.ld-typed');if(typed){const full=typed.dataset.type;if(reduce||paused){typed.textContent=full;wallet.innerHTML=card(0).replace('>Your location<','>'+full+'<').replace('ld-card"','ld-card named"')}else{let k=0;typer=setInterval(()=>{typed.textContent=full.slice(0,++k);const c=wallet.querySelector('.ld-card h3');if(c){c.textContent=full.slice(0,k);wallet.querySelector('.ld-card').classList.add('named')}if(k>=full.length)clearInterval(typer)},85)}}
  demo.classList.toggle('playing',!paused&&!hover);schedule()}
 const schedule=()=>{clearTimeout(timer);if(paused||hover)return;timer=setTimeout(()=>show((i+1)%STEPS.length),DUR[i])}
 const setPaused=p=>{paused=p;pauseBtn.textContent=p?'Play':'Pause';pauseBtn.setAttribute('aria-label',p?'Play the demo':'Pause the demo');demo.classList.toggle('playing',!paused&&!hover);schedule()}
 tabs.forEach((t,j)=>{t.onclick=()=>{show(j,true)};t.onkeydown=e=>{if(e.key==='ArrowRight'||e.key==='ArrowLeft'){e.preventDefault();const n=(j+(e.key==='ArrowRight'?1:STEPS.length-1))%STEPS.length;show(n,true);tabs[n].focus()}}})
 pauseBtn.onclick=()=>setPaused(!paused)
 demo.addEventListener('mouseenter',()=>{hover=true;demo.classList.remove('playing');clearTimeout(timer)});demo.addEventListener('mouseleave',()=>{hover=false;demo.classList.toggle('playing',!paused);schedule()})
 demo.addEventListener('focusin',()=>{hover=true;clearTimeout(timer);demo.classList.remove('playing')});demo.addEventListener('focusout',e=>{if(!demo.contains(e.relatedTarget)){hover=false;demo.classList.toggle('playing',!paused);schedule()}})
 /* Only play while visible. */
 if('IntersectionObserver' in window)new IntersectionObserver(es=>{for(const e of es){if(e.isIntersecting){if(!paused)schedule()}else clearTimeout(timer)}},{threshold:.35}).observe(demo)
 if(reduce){pauseBtn.hidden=true;demo.classList.add('still')}
 show(0);window.FRAN_LANDING_DEMO={show,pause:()=>setPaused(true),play:()=>setPaused(false),scene:()=>i}}

/* What to expect: the real timeline, and what's free and private. */
function expectations(){const host=$('#land-howitworks');if(!host)return;host.className='land-section ld-expect';host.innerHTML=
 '<div class="ld-expect-head"><span class="ls-eyebrow">What to expect</span><h2 class="ls-h2">Your first fifteen minutes,<br>and every month after.</h2><p class="ls-sub">Fran sets the Wallet up with you, one question at a time. You decide what to add, check what it reads, and choose who gets access.</p></div>'+
 '<ol class="ld-timeline">'+[
  ['1 minute','Tell Fran about the location','Name it, say whether it’s open or opening, and what matters next. Fran lays out a plan in the order a franchise actually comes together.','name'],
  ['5 minutes','Bring what you already have','Drop in a whole folder. Fran sorts it and reads the details from your lease, loan and company papers: landlord, rent, CAM, loan terms, EIN, owners. You check each one before it’s saved.','bring'],
  ['Same day','Invite the people who already help','Your accountant, payroll provider, insurance agent or attorney gets a private link for this location only. They connect their part. It’s free.','invite'],
  ['Every month','Keep the picture current','Your business plan tracks against actual results, the Wallet shows what changed, and Fran points to the next thing that needs you.','plan']].map(([time,h,p,k],j)=>'<li><button type="button" class="ld-tl" data-goto="'+['name','bring','invite','plan'][j]+'"><span class="ld-time">'+time+'</span><strong>'+h+'</strong><span class="ld-tl-p">'+p+'</span><span class="ld-tl-cta">See it in the demo ↑</span></button></li>').join('')+'</ol>'+
 '<div class="ld-promises"><div><h3>Free to start</h3><p>One location, all six parts, document reading, invites and your business plan. No card required.</p></div><div><h3>Location Pro, when you want it</h3><p>$49 per location a month for lender and buyer rooms, monthly debt reviews and written answers from Fran.</p></div><div><h3>Private by default</h3><p>Records stay with their location. Connections are read-only. Nothing is shared until you choose who sees what.</p></div></div>'+
 '<div class="ld-expect-cta"><button type="button" class="land-cta-primary" data-start>Start my Wallet: free →</button><span>Set up with Fran takes about two minutes to start.</span></div>'
 host.querySelectorAll('[data-goto]').forEach(b=>b.onclick=()=>{const n=STEPS.findIndex(s=>s.k===b.dataset.goto);document.querySelector('.ld-demo')?.scrollIntoView({behavior:reduce?'auto':'smooth',block:'center'});window.FRAN_LANDING_DEMO?.show(n,true);track('landing_expect_step',{step:b.dataset.goto})})
 host.querySelector('[data-start]').onclick=()=>{track('landing_primary_cta',{placement:'expect'});if(typeof go==='function')go('s-signup')}}
function copy(){const promise=$('.hero-promise');if(promise)promise.textContent='Fran sets up your company, lease, bank, books, payroll and insurance with you, then keeps the picture current.'
 const sub=$('.hero-copy .land-sub');if(sub)sub.textContent='Drop in what you already have. Fran reads it, brings in the people who help you, and shows what needs you next.'
 const sec=$('.hero-copy .land-cta-secondary');if(sec){sec.textContent='See what to expect ↓';sec.onclick=()=>{$('#land-howitworks')?.scrollIntoView({behavior:reduce?'auto':'smooth'});track('landing_expect_opened',{placement:'hero'})}}
 const pulse=$('#land-pulse-text');if(pulse)pulse.textContent='Free to start · No card required · First results in minutes'}
function init(){copy();const demo=mountHero();if(demo)run(demo);expectations();document.body.classList.add('ld-ready')}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init()
})()
