/* Guided setup: choices are browser-local; connections and services remain explicit. */
(()=>{'use strict';
const E=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let state=null,current=null,lifeRecords=[];
// Keep the setup conversation in memory only; never persist financial questions.
let conversation=[],conversationWallet=null;
function conversationFrame(d,title,copy){
 const last=conversation[conversation.length-1];
 if(last?.text!==title)conversation.push({role:'Fran',text:title,detail:copy});
 conversation=conversation.slice(-24);
 const history=document.createElement('details');history.className='setup-conversation';
 history.innerHTML='<summary>Your setup conversation <span>'+E(state?.wallet?.name||'')+'</span></summary><div role="log" aria-label="Setup conversation">'+conversation.map(m=>'<article class="setup-message '+(m.role==='You'?'from-you':'')+'"><small>'+m.role+'</small><p>'+E(m.text)+'</p>'+(m.detail?'<p class="setup-message-detail">'+E(m.detail)+'</p>':'')+'</article>').join('')+'</div>';
 if(conversation.length>1)history.open=true;
 d.querySelector('.setup-body').prepend(history);
 if(d.setupCapture)d.removeEventListener('click',d.setupCapture,true);
 d.setupCapture=e=>{const b=e.target.closest('.setup-body button');if(!b||b.closest('.setup-conversation'))return;const text=(b.querySelector('strong')?.textContent||b.textContent).trim();if(text)conversation.push({role:'You',text:text.slice(0,180)});};
 d.addEventListener('click',d.setupCapture,true);
}
const topics={
 company:{name:'Company & legal',question:'Have you set up the business behind this location?',copy:'Keep the legal entity, ownership and key agreements together. You can start before incorporation.',service:'entity',category:'protection',route:'company',request:'I need formation, registered-agent or attorney help. Please confirm availability, scope, fees and any partner offer before I decide.',choices:['Add company details','I need formation or legal help'],preview:['Legal identity','Ownership','Agreements']},
 bank:{name:'Banking & cards',question:'Do you already have a business bank account or card?',copy:'Bring cash and activity into one view. If you are still choosing an account, start there.',service:'support',category:'money',route:'banking',connector:'bank',request:'Help me compare business banking or cards. Confirm availability, eligibility and partner offers. Do not submit an application.',choices:['Connect an existing account','I need a bank or card'],preview:['Available cash','Account activity','Source date']},
 qbo:{name:'Books & accounting',question:'How are you keeping the books today?',copy:'Connect QuickBooks, bring a report, or get help setting up bookkeeping. You do not need software first.',service:'books',category:'accounting',route:'books',connector:'qbo',request:'Help me set up or outsource bookkeeping. Please explain software options, scope, pricing and any eligible partner offer.',choices:['I have QuickBooks or reports','I need bookkeeping help'],preview:['Revenue','Expenses','Monthly profit']},
 payroll:{name:'Payroll & team',question:'Do you have a payroll provider yet?',copy:'Use the processor you already have, import a report, or explore someone to handle payroll.',service:'payroll',category:'team',route:'payroll',connector:'payroll',request:'Help me choose a payroll processor or outsourced service. Please confirm setup requirements, fees and any eligible offer.',choices:['I have a provider or report','I need a payroll provider'],preview:['Payroll reports','Labor costs','Reporting period']},
 debt:{name:'Loans & financing',question:'Are you tracking a loan—or looking for financing?',copy:'Keep existing obligations organized. If you need funding, prepare a conversation before any application.',service:'support',category:'money',route:'debt',connector:'debt',request:'I need financing guidance or a broker/lender introduction. Confirm availability, fees and applicable offers. Do not apply or pull credit.',choices:['Add an existing loan','I need financing help'],preview:['Lender & terms','Recorded balance','Statement date']},
 insurance:{name:'Insurance & protection',question:'Do you already have coverage for this location?',copy:'Keep your policy and renewal information close, or ask for help finding an agent and coverage.',service:'insurance',category:'protection',route:'insurance',connector:'insurance',request:'Help me find coverage or an insurance agent. Please confirm availability, scope, premiums and applicable offers before I decide.',choices:['I have a policy','I need coverage or an agent'],preview:['Policy documents','Coverage details','Renewal dates']},
 document:{name:'Files & agreements',question:'What is one record you have handy?',copy:'A lease, statement or franchise agreement is enough to start. Keep the original with this location.',service:'support',category:'operations',route:'documents',connector:'document',request:'Help me identify which records to gather first for this location and how to obtain missing documents.',choices:['Add a file I already have','Help me gather my records'],preview:['Private originals','Source dates','Searchable records']}
};
const api=()=>window.FRAN_SETUP_ACTIONS;
function track(action,topic){try{window.posthog?.capture('wallet_setup_'+action,{topic:topic||'overview'})}catch(_){}}
function prefs(){try{return JSON.parse(localStorage.getItem('fran_setup_choices:'+state.wallet.id)||'{}')}catch(_){return {}}}
function defer(id){const p=prefs();p[id]='later';try{localStorage.setItem('fran_setup_choices:'+state.wallet.id,JSON.stringify(p))}catch(_){}track('deferred',id);advance()}
function has(id){if(id==='company')return[...(state?.records||[]),...lifeRecords].some(r=>r.kind==='entity'&&(r.data?.legal_name||r.data?.name||r.data?.ein));if(id==='insurance')return(state?.records||[]).some(r=>r.kind==='insurance'||r.kind==='document'&&(r.data?.category==='Insurance'||/^insurance_/.test(r.data?.document_type||'')||/insurance|\bcoi\b/i.test(r.data?.name||'')));return api()?.connected(id)||false}
function dialog(title,copy,body){let d=document.getElementById('fran-connectors');if(!d){d=document.createElement('dialog');d.id='fran-connectors';d.className='fran-connectors';document.body.append(d)}d.classList.add('fran-setup-dialog');d.setAttribute('aria-labelledby','fran-connectors-title');d.innerHTML='<header><div><span class="setup-wordmark">F. <small>YOUR WALLET GUIDE</small></span><h2 id="fran-connectors-title">'+E(title)+'</h2><p>'+E(copy)+'</p></div><button class="fran-connectors-close" aria-label="Close setup guide">×</button></header><div class="setup-body">'+body+'</div>';d.querySelector('.fran-connectors-close').onclick=()=>d.close();conversationFrame(d,title,copy);if(!d.open&&!window.FRAN_JOURNEY?.active?.())d.showModal();requestAnimationFrame(()=>d.querySelector('.setup-body button')?.focus());return d}
function sendProviderDraft(id){const t=topics[id];document.getElementById('fran-connectors')?.close();track('provider_draft',id);window.switchTab?.('services');dispatchEvent(new CustomEvent('fran:service-message',{detail:{service:t.service,note:t.request}}));handoff(id,'services')}
function market(id){document.getElementById('fran-connectors')?.close();track('tools_opened',id);dispatchEvent(new CustomEvent('fran:marketplace-open',{detail:{category:topics[id].category}}));remember(id);handoff(id,'marketplace')}
function existing(id){track('existing_selected',id);document.getElementById('fran-connectors')?.classList.remove('fran-setup-dialog');if(topics[id].connector)api().preflight(topics[id].connector);else{document.getElementById('fran-connectors')?.close();window.switchTab?.(id==='company'?'entity':topics[id].route)}}
function overview(){if(!state?.wallet||state.wallet.access_role)return;current=null;const p=prefs(),goal=api()?.profile();if(!goal)return api()?.goalGuide();const ready=Object.keys(topics).filter(has).length;const d=dialog('Build your Wallet, one useful step at a time.',state.wallet.name+' · Start with what you have. We’ll help with what you don’t.','<div class="setup-intro"><span>'+ready+' areas with saved information</span><p>You do not need to finish every area. Pick the one that would help you today.</p></div><div class="setup-plan">'+Object.entries(topics).map(([id,t])=>'<button data-area="'+id+'"><span class="setup-dot">'+(has(id)?'✓':p[id]?'↗':'+')+'</span><span><strong>'+E(t.name)+'</strong><small>'+E(has(id)?'Review saved information':p[id]?'Saved for later · resume anytime':t.preview.join(' · '))+'</small></span><b>→</b></button>').join('')+'</div><form class="setup-prompt"><label for="setup-question">Or tell Fran where you want to start</label><div><input id="setup-question" maxlength="300" placeholder="I don’t have a bookkeeper yet" autocomplete="off"><button>Continue</button></div><p role="status" id="setup-feedback">Try “I need insurance” or “connect my bank.”</p></form><p class="setup-footnote">Your goal is saved to your wallet. “Not now” choices are remembered on this browser.</p>');d.querySelectorAll('[data-area]').forEach(b=>b.onclick=()=>area(b.dataset.area));d.querySelector('form').onsubmit=e=>{e.preventDefault();const q=d.querySelector('input').value.toLowerCase();const id=/entity|legal|attorney|agent|incorporat/.test(q)?'company':/insurance|policy|coverage/.test(q)?'insurance':/book|accountant|qbo|profit/.test(q)?'qbo':/payroll|employee|gusto/.test(q)?'payroll':/loan|lender|broker|debt|financ/.test(q)?'debt':/bank|card|cash|plaid/.test(q)?'bank':/file|document|lease|agreement/.test(q)?'document':null;if(id)area(id);else d.querySelector('#setup-feedback').textContent='Choose an area above so I can take you to the right setup step.'};track('opened')}
const goalCopy={maintain:'a clearer operating picture',financing:'a better-prepared financing conversation',exit:'a more organized future-sale record',both:'financing and future-sale readiness'};
const payoff={company:['Company details','A clear legal identity','Confirm who owns and operates this location.'],bank:['An existing account','Your cash picture','Review balances and activity with the source date beside them.'],qbo:['QuickBooks or a report','Your monthly profit picture','Review revenue, costs and the period behind the result.'],payroll:['A payroll connection or report','Your labor-cost picture','Review the report period before comparing costs.'],debt:['A loan record or statement','Your debt picture','See recorded balances, payments and dates together.'],insurance:['A policy document','Your coverage record','Find policy details and renewal dates in the same place.'],document:['One original document','Your first saved record','Keep the original close and check what can be read from it.']};
function remember(id){try{localStorage.setItem('fran_setup_resume:'+state.wallet.id,id)}catch(_){}}
function remembered(){try{return localStorage.getItem('fran_setup_resume:'+state.wallet.id)}catch(_){return null}}
function clearResume(){try{localStorage.removeItem('fran_setup_resume:'+state.wallet.id)}catch(_){}}
function nextTopic(){const goal=api()?.profile()?.goal,p=prefs(),order=goal==='financing'?['debt','qbo','bank','document','company','insurance','payroll']:goal==='exit'||goal==='both'?['document','qbo','company','debt','insurance','bank','payroll']:['qbo','bank','document','payroll','insurance','company','debt'];if(state?.wallet?.operating_status==='preopening'){order.splice(order.indexOf('company'),1);order.unshift('company')}return order.find(id=>!has(id)&&p[id]!=='later')}
function start(){if(!state?.wallet||state.wallet.access_role)return;if(!api()?.profile())return api()?.goalGuide();const resume=remembered();if(topics[resume])return has(resume)?result(resume):area(resume);const next=nextTopic();if(next)return area(next);finish()}
function advance(){clearResume();const next=nextTopic();if(next)area(next);else finish()}
function finish(){const saved=Object.keys(topics).filter(has),d=dialog(saved.length?'Your Wallet has a starting point.':'You can build this at your own pace.',saved.length?'Review one saved source before adding more. You do not need to finish every area today.':'The areas you deferred are still available. Start again whenever you have a record—or want help getting one.','<div class="setup-finish"><span class="setup-finish-mark" aria-hidden="true">'+(saved.length?'✓':'↗')+'</span><h3>'+ (saved.length?'Make the first source useful.':'Nothing has been connected yet.')+'</h3><p>'+E(saved.length?topics[saved[0]].name+' has saved information. Check its source date and coverage.':'Deferring a step does not complete it or create an account.')+'</p><button data-finish-primary>'+E(saved.length?'Review '+topics[saved[0]].name:'Choose a step to revisit')+' →</button><button data-finish-plan>View my setup plan</button></div>');d.querySelector('[data-finish-primary]').onclick=()=>saved.length?review(saved[0]):overview();d.querySelector('[data-finish-plan]').onclick=overview;track('checkpoint')}
function review(id){document.getElementById('fran-connectors')?.close();window.switchTab?.(topics[id].route);track('result_opened',id);handoff(id)}
function result(id){const t=topics[id],d=dialog('A source is in place. Let’s put it to work.',state.wallet.name+' · '+t.name,'<div class="setup-value-preview"><small>YOUR NEXT USEFUL ACTION</small><h3>'+E(payoff[id][1])+'</h3><p>'+E(payoff[id][2])+'</p><p class="setup-footnote">Saved information is not a completeness check. Review dates, missing fields and source coverage.</p></div><div class="setup-result-actions"><button data-review>Open '+E(t.name)+' →</button><button data-continue>Continue setup</button></div>');d.querySelector('[data-review]').onclick=()=>review(id);d.querySelector('[data-continue]').onclick=advance;track('source_checkpoint',id)}
function handoff(id,destination){const t=topics[id],page=document.getElementById('page-'+(destination||(id==='company'?'entity':id==='insurance'&&!has(id)?'documents':t.route)));if(!page)return;document.querySelectorAll('.setup-return').forEach(x=>x.remove());const box=document.createElement('aside');box.className='setup-return';box.innerHTML='<div><strong>'+E(destination?'Your setup plan is still here.':has(id)?'Review your source, then choose your next step.':'Your setup guide is still here.')+'</strong><p>'+E(destination?'Explore at your own pace. Browsing tools or preparing a request does not activate a service.':has(id)?'Check the reporting dates and what is included.':'Finish the connection or add your record below. If it is not ready, you can choose another path.')+'</p></div><button type="button">'+(has(id)?'Continue setup':'Return to setup')+' →</button>';page.prepend(box);box.querySelector('button').onclick=()=>has(id)?result(id):area(id)}
function area(id){if(!topics[id]||!state?.wallet||state.wallet.access_role)return;current=id;const t=topics[id],value=payoff[id],goal=goalCopy[api()?.profile()?.goal]||'your next business decision',d=dialog(t.question,t.copy,
 '<nav class="setup-trail" aria-label="Setup stages"><span aria-current="step"><b>1</b> Choose your path</span><span><b>2</b> Add a source</span><span><b>3</b> Review the result</span></nav><div class="setup-value-preview"><small>'+E(state.wallet.name)+' · '+E(t.name)+'</small><h3>'+E(value[1])+'</h3><p>'+E(value[2])+'</p><div class="setup-evidence-flow"><span>'+E(value[0])+'</span><b aria-hidden="true">→</b><span>Your Wallet</span></div><details><summary>Why start here?</summary><p>This helps you work toward '+E(goal)+'. '+E(t.copy)+' This is optional; you can choose another area.</p></details></div><div class="setup-answers"><button data-existing><strong>'+E(has(id)?'Review my saved information':t.choices[0])+'</strong><span>'+E(has(id)?'Check the source and its dates before adding more.':'I’ll show you what to add and what Fran can use.')+'</span><b>→</b></button><button data-provider><strong>'+E(t.choices[1])+'</strong><span>Let’s find the right kind of help first.</span><b>→</b></button></div><div class="setup-secondary"><button data-file>Add a document instead</button><button data-market>Explore apps & offers</button></div><div class="setup-bottom"><button data-back>← Choose a different area</button><button data-later>Skip for now →</button></div><p class="setup-footnote">No need to complete every area. Your connections require your authorization; provider requests stay drafts until you send them.</p>');
 d.querySelector('[data-back]').onclick=overview;d.querySelector('[data-existing]').onclick=()=>{if(has(id))return result(id);remember(id);existing(id);handoff(id)};d.querySelector('[data-provider]').onclick=()=>provider(id);d.querySelector('[data-market]').onclick=()=>market(id);d.querySelector('[data-file]').onclick=()=>window.FRAN_SETUP_JOURNEY.addFile();d.querySelector('[data-later]').onclick=()=>defer(id);track('area_opened',id)}
function provider(id){const t=topics[id],d=dialog('You don’t need to figure this out alone.',t.name+' · Choose how you would like to move forward.','<button class="setup-back" data-provider-back>← Back to the question</button><div class="setup-value-preview"><small>HANDS-ON HELP</small><h3>'+E(t.choices[1])+'</h3><p>We’ll prepare a short request for the CoverPanda service team. You can edit it, review who receives it, and decide whether to send.</p><details><summary>What happens after I send a request?</summary><p>Your request appears in your service inbox. Availability, scope, price and any eligible partner benefit must be confirmed. A request does not start a paid service.</p></details></div><div class="setup-answers"><button data-draft><strong>Prepare my request</strong><span>Review the message and consent before sending.</span><b>→</b></button><button data-provider-tools><strong>I’d rather explore tools myself</strong><span>Open relevant apps and available offer information.</span><b>→</b></button></div><p class="setup-footnote">No application, purchase or service enrollment happens in this guide.</p>');d.querySelector('[data-provider-back]').onclick=()=>area(id);d.querySelector('[data-draft]').onclick=()=>{remember(id);sendProviderDraft(id)};d.querySelector('[data-provider-tools]').onclick=()=>market(id)}
window.openFranSetup=start;
window.openFranSetupPlan=overview;
window.FRAN_SETUP_JOURNEY={
 catalog:()=>Object.entries(topics).map(([id,t])=>({id,name:t.name,route:t.route,question:t.question,copy:t.copy,choices:t.choices,preview:t.preview,saved:has(id),value:payoff[id][1]})),
 next:nextTopic,
 resume:remembered,
 clearResume,
 addFile:()=>{if(!state?.wallet||state.wallet.access_role)return;remember('document');window.FRAN_SETUP_ACTIONS?.addFile?.();handoff('document')},
 connect:id=>{if(!topics[id]||!state?.wallet||state.wallet.access_role)return;remember(id);existing(id);handoff(id)},
 draft:id=>{if(!topics[id]||!state?.wallet||state.wallet.access_role)return;remember(id);sendProviderDraft(id)},
 market:id=>{if(topics[id]&&state?.wallet&&!state.wallet.access_role)market(id)},
 review:id=>{if(topics[id]&&state?.wallet&&!state.wallet.access_role)review(id)},
 skip:id=>{if(!topics[id]||!state?.wallet||state.wallet.access_role)return;const p=prefs();p[id]='later';try{localStorage.setItem('fran_setup_choices:'+state.wallet.id,JSON.stringify(p))}catch(_){}clearResume();track('deferred',id)}
};
function emptyStates(){document.querySelectorAll('.fran-empty-start').forEach(e=>e.remove());if(!state?.wallet||state.wallet.access_role)return;Object.entries(topics).forEach(([id,t])=>{if(has(id))return;const page=document.getElementById('page-'+t.route);if(!page)return;const box=document.createElement('section');box.className='fran-empty-start';box.innerHTML='<div><small>MAKE THIS PART OF YOUR WALLET</small><h2>'+E(t.question)+'</h2><p>'+E(t.copy)+'</p></div><div class="setup-empty-actions"><button data-start>Help me get started →</button><button data-provider>'+E(t.choices[1])+'</button><button data-market>Explore tools & offers</button></div>';const header=page.querySelector('.main-hdr');if(header)header.after(box);else page.prepend(box);box.querySelector('[data-start]').onclick=()=>area(id);box.querySelector('[data-provider]').onclick=()=>provider(id);box.querySelector('[data-market]').onclick=()=>market(id)})}
window.addEventListener('fran:location',e=>{if(conversationWallet!==e.detail?.wallet?.id){conversation=[];lifeRecords=[];conversationWallet=e.detail?.wallet?.id;document.getElementById('fran-connectors')?.close()}state=e.detail;current=null;document.querySelectorAll('.setup-return').forEach(x=>x.remove());emptyStates();if(state?.wallet&&topics[remembered()])handoff(remembered())});
window.addEventListener('fran:readiness',e=>{if(!state?.wallet||e.detail?.location?.wallet?.id!==state.wallet.id)return;lifeRecords=e.detail.life?.records||[];emptyStates()});
})();
