/* Business plan: build one with Fran or connect the one you have, keep it current, and print a lender summary.
   Assumptions are the owner's; values the Wallet already knows (lease occupancy, loan payments, QuickBooks results)
   are prefilled and labeled with their source. Projections are calculated live and never stored. */
(()=>{'use strict'
const $=id=>document.getElementById(id),E=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))
const C=()=>window.FranBizPlanCore,X=()=>window.FranExtract,metric=(n,p)=>{try{window.posthog?.capture(n,p)}catch(_){}}
let loc=null,life=null,draft=null,dirty=false
const owned=()=>!!loc?.wallet&&!loc.wallet.access_role
const usd=(v,d=0)=>v===null||v===undefined||v===''||!Number.isFinite(Number(v))?'—':new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',minimumFractionDigits:d,maximumFractionDigits:d}).format(Number(v))
const short=v=>{const n=Number(v);if(!Number.isFinite(n))return '—';const a=Math.abs(n);return (n<0?'−':'')+'$'+(a>=1e6?(a/1e6).toFixed(a>=1e7?0:1)+'M':a>=1e3?Math.round(a/1e3)+'K':Math.round(a))}
const ym=s=>s?new Date(s+'-01T12:00:00Z').toLocaleDateString('en-US',{month:'short',year:'numeric',timeZone:'UTC'}):'—'
const today=()=>new Date().toISOString().slice(0,10)
const records=k=>(life?.records||[]).filter(r=>r.kind===k)
const saved=()=>records('business_plan')[0]?.data||null
const entity=()=>records('entity')[0]?.data||null
const finances=()=>{try{return window.FranWalletModel?.finances?.(loc)||[]}catch(_){return []}}
async function api(fn,action,body){const {data:{session}}=await sb.auth.getSession();if(!session)throw Error('Please sign in again.')
 const r=await fetch(SUPABASE_URL+'/functions/v1/'+fn,{method:'POST',headers:{'Content-Type':'application/json',apikey:SUPABASE_ANON_KEY,Authorization:'Bearer '+session.access_token},body:JSON.stringify({action,wallet_id:loc.wallet.id,...body})})
 const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||'That didn’t save. Please try again.');return d}

/* Starting assumptions are offered only where the Wallet knows nothing, and always labeled. */
const START={cogs_pct:30,labor_pct:28,royalty_pct:6,marketing_pct:2}
function wallet(){const pre=C().prefill({lease:records('lease')[0]?.data,loans:records('loan').map(r=>r.data),finances:finances(),loanSchedule:X()?.schedule});return pre}
function newPlan(stage){const pre=wallet(),a={start_month:stage==='preopening'?'':C().thisMonth(),months:36,revenue_start:pre.values.revenue_start??null,growth_pct:stage==='preopening'?3:3,ramp_months:stage==='preopening'?6:0,ramp_start_pct:stage==='preopening'?60:100,cogs_pct:pre.values.cogs_pct??START.cogs_pct,labor_pct:pre.values.labor_pct??START.labor_pct,royalty_pct:START.royalty_pct,marketing_pct:START.marketing_pct,rent_monthly:pre.values.rent_monthly??null,other_monthly:null,debt_service_monthly:pre.values.debt_service_monthly??null,sources:{...pre.sources}}
 for(const k of Object.keys(START))if(!a.sources[k])a.sources[k]='Starting assumption: replace with your franchisor’s or your own numbers'
 const owners=(entity()?.owners||[]).filter(o=>o?.name),loan=records('loan')[0]?.data
 return {purpose:stage==='preopening'?'launch':'operate',stage,opening_date:'',summary:'',concept:loc?.wallet?.brand&&!String(loc?.wallet?.name||'').toLowerCase().includes(String(loc.wallet.brand).toLowerCase())?loc.wallet.brand+' · '+loc.wallet.name:(loc?.wallet?.name||''),market:'',team:owners.map(o=>o.name+(o.percentage!=null?' ('+o.percentage+'%)':'')).join(', '),marketing:'',
  uses:stage==='preopening'?[{label:'Build-out and construction',amount:null},{label:'Equipment',amount:null},{label:'Franchise fee',amount:null},{label:'Working capital',amount:null}]:[],
  sources:stage==='preopening'?[{label:'Owner equity',amount:null,kind:'equity'},...(loan?[{label:(loan.loan_type||'Loan')+' · '+loan.lender,amount:loan.amount,kind:'loan'}]:[])]:[],
  assumptions:a,actuals:{},documents:[],revisions:[]}}
async function persist(plan,note){const revisions=[{at:today(),note:note||'Updated'},...(plan.revisions||[])].slice(0,30)
 const data={...plan,revisions};await api('lifecycle','save',{kind:'business_plan',request_id:'plan',data});try{await window.refreshLocation?.(true)}catch(_){}return data}

/* ---------- chart: monthly revenue bars with an EBITDA line ---------- */
function chart(p){if(!p)return '';const rows=p.rows,W=760,H=200,pad=28,max=Math.max(...rows.map(r=>r.revenue)),min=Math.min(0,...rows.map(r=>r.ebitda)),span=max-min||1,x=i=>pad+i*(W-pad*2)/rows.length,y=v=>H-pad-(v-min)/span*(H-pad*2),bw=(W-pad*2)/rows.length*0.62
 const bars=rows.map((r,i)=>'<rect x="'+x(i).toFixed(1)+'" y="'+y(r.revenue).toFixed(1)+'" width="'+bw.toFixed(1)+'" height="'+Math.max(0,y(0)-y(r.revenue)).toFixed(1)+'" rx="2" class="bp-bar"/>').join('')
 const line=rows.map((r,i)=>(i?'L':'M')+(x(i)+bw/2).toFixed(1)+' '+y(r.ebitda).toFixed(1)).join(' ')
 const ticks=rows.filter((_,i)=>i%6===0).map(r=>'<text x="'+(x(r.n-1)+bw/2).toFixed(1)+'" y="'+(H-8)+'" class="bp-tick">'+ym(r.month)+'</text>').join('')
 return '<figure class="bp-chart"><svg viewBox="0 0 '+W+' '+H+'" role="img" aria-labelledby="bp-chart-t"><title id="bp-chart-t">Projected monthly revenue with EBITDA, '+ym(rows[0].month)+' to '+ym(rows.at(-1).month)+'</title><line x1="'+pad+'" x2="'+(W-pad)+'" y1="'+y(0).toFixed(1)+'" y2="'+y(0).toFixed(1)+'" class="bp-zero"/>'+bars+'<path d="'+line+'" class="bp-line"/>'+ticks+'</svg><figcaption><span class="bp-key bar"></span>Revenue <span class="bp-key line"></span>EBITDA · calculated from your assumptions</figcaption></figure>'}

/* ---------- the page ---------- */
const FIELDS=[['opening_cash','Starting cash','money','Cash available at the start of this scenario'],['taxes_monthly','Cash taxes','money','Planned monthly cash payment'],['capex_monthly','Capital spending','money','Equipment and capital projects per month'],['working_capital_monthly','Working capital investment','money','Additional cash absorbed per month'],['distributions_monthly','Owner distributions','money','Planned monthly cash outflow'],['revenue_start','Monthly revenue','money','Once established'],['growth_pct','Annual growth','pct'],['ramp_months','Opening ramp','months','Months to reach full revenue'],['ramp_start_pct','Ramp starts at','pct','Of full revenue'],['cogs_pct','Cost of goods','pct','% of revenue'],['labor_pct','Labor','pct','% of revenue'],['royalty_pct','Royalty','pct','% of revenue'],['marketing_pct','Brand marketing fund','pct','% of revenue'],['rent_monthly','Occupancy','money','Rent + CAM per month'],['other_monthly','Other operating costs','money','Utilities, software, repairs… per month'],['debt_service_monthly','Debt payments','money','Per month'],['start_month','Projection starts','month'],['months','Months projected','months']]
function field(a,[k,label,type,hint]){const v=a[k]??'',src=a.sources?.[k]||'',start=/^Starting assumption/.test(src)
 return '<label class="bp-field'+(src?(start?' start':' from'):'')+'"><span>'+E(label)+'</span><div class="bp-in">'+(type==='money'?'<em>$</em>':'')+'<input data-a="'+k+'" type="'+(type==='month'?'month':'number')+'"'+(type==='pct'?' step="0.1"':type==='money'?' step="1" min="0"':type==='months'?' step="1" min="0" max="60"':'')+' value="'+E(v)+'">'+(type==='pct'?'<em>%</em>':'')+'</div><small>'+E(src||hint||'')+'</small></label>'}
function rowsEditor(list,kind){return list.map((u,i)=>'<div class="bp-row" data-list="'+kind+'" data-i="'+i+'"><input data-f="label" aria-label="'+(kind==='uses'?'Use of funds':'Source of funds')+'" value="'+E(u.label)+'" placeholder="'+(kind==='uses'?'What it pays for':'Where it comes from')+'">'+(kind==='sources'?'<select data-f="kind" aria-label="Type"><option value="equity"'+(u.kind==='equity'?' selected':'')+'>Equity</option><option value="loan"'+(u.kind==='loan'?' selected':'')+'>Loan</option><option value="other"'+(u.kind==='other'?' selected':'')+'>Other</option></select>':'')+'<div class="bp-in"><em>$</em><input data-f="amount" type="number" min="0" step="1" aria-label="Amount" value="'+E(u.amount??'')+'"></div><button type="button" class="bp-x" data-remove aria-label="Remove">×</button></div>').join('')}
function results(p,plan){if(!p)return '<p class="bp-empty-note">Add monthly revenue to see projections.</p>';const y1=p.years[0],gap=C().fundingGap(plan),a=plan.assumptions||{},missing=[['other_monthly','other operating costs'],['rent_monthly','occupancy']].filter(([k])=>!(Number(a[k])>0)).map(x=>x[1])
 return (missing.length?'<p class="bp-warn" role="note">No '+missing.join(' or ')+' entered yet, so these results are optimistic. Add them for numbers a lender will trust.</p>':'')+'<div class="bp-kpis"><div><span>Year 1 revenue</span><strong>'+usd(y1.revenue)+'</strong></div><div><span>Year 1 EBITDA</span><strong>'+usd(y1.ebitda)+'</strong><small>'+y1.margin+'% margin</small></div><div class="'+(y1.dscr!==null&&y1.dscr<1.25?'warn':'')+'"><span>Debt coverage (DSCR)</span><strong>'+(y1.dscr===null?'No debt':y1.dscr.toFixed(2)+'×')+'</strong><small>'+(y1.dscr===null?'':y1.dscr<1?'Doesn’t cover payments':y1.dscr<1.25?'Below the 1.25× lenders often look for':'Covers payments')+'</small></div><div><span>Break-even</span><strong>'+(p.break_even?ym(p.break_even):'Not in range')+'</strong><small>'+(p.cash_positive?'Cash after debt from '+ym(p.cash_positive):'Cash after debt stays negative')+'</small></div></div>'+chart(p)+
 '<div class="bp-table" tabindex="0" role="region" aria-label="Annual projections"><table><thead><tr><th></th>'+p.years.map(y=>'<th>Year '+y.year+'</th>').join('')+'</tr></thead><tbody>'+[['Revenue','revenue'],['Cost of goods','cogs'],['Labor','labor'],['Royalty','royalty'],['Marketing fund','marketing'],['Occupancy','occupancy'],['Other operating','other'],['EBITDA','ebitda'],['Debt payments','debt'],['Cash after debt','cash'],['Cash taxes','taxes'],['Capital spending','capex'],['Working capital investment','workingCapital'],['Owner distributions','distributions'],['Net cash movement','cashMovement'],['Ending scenario cash','endingCash']].map(([l,k])=>'<tr class="'+(k==='ebitda'||k==='cash'?'sum':'')+'"><th>'+l+'</th>'+p.years.map(y=>'<td>'+usd(y[k])+'</td>').join('')+'</tr>').join('')+'<tr><th>DSCR</th>'+p.years.map(y=>'<td>'+(y.dscr===null?'—':y.dscr.toFixed(2)+'×')+'</td>').join('')+'</tr></tbody></table></div>'+(gap.uses?'':'')}
function trackingHTML(p,plan){const rows=C().compare(p,{finances:finances(),entered:plan.actuals||{}}).slice(-12);if(!rows.length)return '<p class="bp-empty-note">Tracking starts '+(p?ym(p.rows[0].month):'when the projection starts')+'. Connect QuickBooks and actual results fill in by themselves, or enter monthly revenue here.</p>'
 return '<div class="bp-table" tabindex="0" role="region" aria-label="Plan versus actual"><table><thead><tr><th>Month</th><th>Plan</th><th>Actual</th><th>Difference</th></tr></thead><tbody>'+rows.map(r=>'<tr><th>'+ym(r.month)+'</th><td>'+usd(r.plan)+'</td><td>'+(r.source==='books'?usd(r.actual)+'<small class="bp-badge">QuickBooks</small>':'<div class="bp-in"><em>$</em><input data-actual="'+r.month+'" type="number" min="0" step="1" aria-label="Actual revenue '+ym(r.month)+'" value="'+E(r.actual??'')+'"></div>')+'</td><td class="'+(r.pct===null?'':r.pct<0?'neg':'pos')+'">'+(r.pct===null?'—':(r.pct>0?'+':'')+r.pct+'% · '+usd(r.variance))+'</td></tr>').join('')+'</tbody></table></div>'}
function page(){let p=$('page-bizplan');if(p)return p;const main=document.querySelector('#view-wallet .main');if(!main)return null;p=document.createElement('div');p.className='page';p.id='page-bizplan';main.append(p);return p}
function navItem(){if(!owned()){$('bp-nav')?.remove();return}if($('bp-nav'))return;const nav=$('release-nav');if(!nav)return;const b=document.createElement('button');b.type='button';b.id='bp-nav';b.className='nav-item release-nav';b.dataset.page='bizplan';b.innerHTML='<span>Business plan</span>';b.onclick=()=>open();const before=$('fran-hub-nav')||nav.querySelector('[data-page=settings]');before?before.before(b):nav.append(b)}
function planningHeader(plan){return '<section class="bp-workspace"><span>YOUR BUSINESS PLANNING FOLDER</span><h2>One plan. Every next chapter.</h2><p>Keep your startup costs, projections, supporting records and funding story together. Your assumptions stay editable and saved versions keep their history.</p><nav aria-label="Business planning workspace"><button type="button" data-bp-jump="Projections">Projections & cash after debt</button><button type="button" data-bp-jump="Sources & uses">Startup & funding</button><button type="button" data-bp-jump="Documents">Planning documents</button><button type="button" data-bp-room>Loan & data rooms →</button></nav><small>Cash after debt is an operating scenario, not a full cash-flow statement. Add cash taxes, working capital, capital spending, distributions and starting cash to model your ending scenario balance. Blank inputs are treated as zero, not verified facts.</small></section>';}
function planningFolders(host,plan){host.querySelector('.bp-workspace')?.remove();const hdr=host.querySelector('.main-hdr');if(!hdr)return;hdr.insertAdjacentHTML('afterend',planningHeader(plan));host.querySelectorAll('[data-bp-jump]').forEach(b=>b.onclick=()=>{const target=[...host.querySelectorAll('.bp-card')].find(c=>c.querySelector('h2')?.textContent===b.dataset.bpJump);if(target){target.scrollIntoView({block:'start',behavior:'smooth'});target.querySelector('input,button,select,textarea')?.focus();}else if(!plan){host.querySelector('[data-start=fresh]')?.click();setTimeout(()=>host.querySelector('[data-bp-jump="'+b.dataset.bpJump+'"]')?.click(),0);}else if(b.dataset.bpJump==='Sources & uses'){draft={...plan,purpose:'financing'};dirty=true;render();setTimeout(()=>host.querySelector('[data-bp-jump="Sources & uses"]')?.click(),0);}});host.querySelector('[data-bp-room]').onclick=()=>window.switchTab?.('dataroom');}
function render(){const host=page();if(!host)return;navItem();if(!owned()){host.innerHTML='';return}
 const plan=draft||(saved()?structuredClone(saved()):null),name=loc.wallet.name,stage=plan?.stage||((records('entity')[0]?.data?.operating_status==='preopening')?'preopening':'operating')
 if(!plan){host.innerHTML='<div class="main-hdr"><h1>Business plan</h1></div><section class="bp-start"><div class="bp-start-copy"><small>'+E(name.toUpperCase())+'</small><h2>'+(stage==='preopening'?'Put your opening plan on paper.':'Keep your plan as current as your books.')+'</h2><p>'+(stage==='preopening'?'What it costs to open, how you’ll fund it, and what the first three years look like. It’s what a lender asks for, built from what your Wallet already knows.':'Projections that start from your real numbers, a plan you can update in minutes, and a clear view of plan versus actual every month.')+'</p></div><div class="bp-start-choices"><button type="button" data-start="fresh"><strong>Build it with Fran</strong><span>'+(stage==='preopening'?'Start fresh: costs, funding and projections':'Start from your current results')+'</span></button><button type="button" data-start="existing"><strong>Connect your existing plan</strong><span>Add the business plan or projections you already have</span></button></div></section>'
  host.querySelector('[data-start=fresh]').onclick=()=>{draft=newPlan(stage);dirty=true;render();metric('bizplan_started',{mode:'fresh',stage})}
  host.querySelector('[data-start=existing]').onclick=()=>connectExisting(stage);planningFolders(host,null);return}
 const a=plan.assumptions||{},p=C().project(a),gap=C().fundingGap(plan),last=plan.revisions?.[0]
 host.innerHTML='<div class="main-hdr bp-hdr"><div><h1>Business plan</h1><p class="bp-sub">'+E(name)+(last?' · updated '+E(new Date(last.at+'T12:00:00Z').toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric',timeZone:'UTC'})):' · not saved yet')+'</p></div><div class="bp-actions"><button type="button" class="bp-ghost" data-summary>Lender summary</button></div></div>'+
 '<section class="bp-card"><h2>The business</h2><div class="bp-grid2"><label class="bp-field"><span>What this plan is for</span><select data-p="purpose">'+[['launch','Opening this location'],['financing','Financing or refinancing'],['growth','Growing this location'],['sale','Preparing for a sale'],['operate','Running it well']].map(([v,l])=>'<option value="'+v+'"'+(plan.purpose===v?' selected':'')+'>'+l+'</option>').join('')+'</select></label>'+(plan.stage==='preopening'?'<label class="bp-field"><span>Opening date</span><input data-p="opening_date" type="date" value="'+E(plan.opening_date||'')+'"></label>':'')+'</div>'+
  [['summary','Summary','In a few sentences: what this location is and why it will work.'],['concept','Concept','Brand, format, and what you sell.'],['market','Market','Who your customers are and what’s nearby.'],['team','Team','Owners and the people running it.'],['marketing','Marketing','How you’ll bring people in.']].map(([k,l,h])=>'<label class="bp-field wide"><span>'+l+'</span><textarea data-p="'+k+'" rows="'+(k==='summary'?3:2)+'" placeholder="'+E(h)+'">'+E(plan[k]||'')+'</textarea></label>').join('')+'</section>'+
 (plan.stage==='preopening'||plan.purpose==='financing'||(plan.uses||[]).length?'<section class="bp-card"><h2>Sources & uses</h2><p class="bp-hint">What it takes to open, and where the money comes from.</p><div class="bp-su"><div><h3>Uses</h3><div data-rows="uses">'+rowsEditor(plan.uses||[],'uses')+'</div><button type="button" class="bp-link" data-add="uses">+ Add a use</button><p class="bp-total">Total '+usd(gap.uses)+'</p></div><div><h3>Sources</h3><div data-rows="sources">'+rowsEditor(plan.sources||[],'sources')+'</div><button type="button" class="bp-link" data-add="sources">+ Add a source</button><p class="bp-total">Total '+usd(gap.sources)+'</p></div></div><p class="bp-gap '+(gap.gap>0?'short':gap.uses?'ok':'')+'">'+(!gap.uses?'Add your costs to see the funding picture.':gap.gap>0?'You’re '+usd(gap.gap)+' short of funding the plan.':gap.gap<0?'Funding exceeds costs by '+usd(-gap.gap)+'.':'Fully funded.')+'</p></section>':'')+
 '<section class="bp-card"><h2>Projections</h2><p class="bp-hint">Change any assumption and the numbers update. Values marked from your Wallet came from your records.</p><div class="bp-fields">'+FIELDS.filter(f=>plan.stage==='preopening'||!['ramp_months','ramp_start_pct'].includes(f[0])).map(f=>field(a,f)).join('')+'</div><div data-results>'+results(p,plan)+'</div></section>'+
 '<section class="bp-card"><h2>Plan vs. actual</h2><div data-track>'+trackingHTML(p,plan)+'</div>'+(plan.revisions?.length?'<details class="bp-history"><summary>Revision history · '+plan.revisions.length+'</summary><ul>'+plan.revisions.map(r=>'<li><strong>'+E(r.at)+'</strong> '+E(r.note)+'</li>').join('')+'</ul></details>':'')+'</section>'+
 '<section class="bp-card"><h2>Documents</h2>'+((plan.documents||[]).length?'<ul class="bp-docs">'+plan.documents.map(d=>'<li><span>'+E(d.name)+'</span><small>'+E({business_plan:'Business plan',projections:'Projections',other:'Supporting document'}[d.kind]||'Document')+'</small></li>').join('')+'</ul>':'<p class="bp-empty-note">Attach the business plan, projections or pitch you already have.</p>')+'<button type="button" class="bp-link" data-attach>+ Attach a document</button></section>'+
 '<div class="bp-savebar'+(dirty?' on':'')+'" role="region" aria-label="Save plan"><span>'+(dirty?'Unsaved changes':'All changes saved')+'</span><input data-note placeholder="What changed? (optional)" aria-label="What changed"><button type="button" class="bp-save" data-save'+(dirty?'':' disabled')+'>Save plan</button><p class="bp-err" role="alert"></p></div>'
 bind(host,plan)}
function bind(host,plan){const update=()=>{dirty=true;const a=plan.assumptions,p=C().project(a);host.querySelector('[data-results]').innerHTML=results(p,plan);host.querySelector('[data-track]').innerHTML=trackingHTML(p,plan);bar()}
 const bar=()=>{const b=host.querySelector('.bp-savebar');b.classList.toggle('on',dirty);b.querySelector('span').textContent=dirty?'Unsaved changes':'All changes saved';b.querySelector('[data-save]').disabled=!dirty}
 draft=plan
 planningFolders(host,plan);
 if(!plan.assumptions)plan.assumptions={};host.querySelectorAll('[data-a]').forEach(el=>el.oninput=()=>{const k=el.dataset.a;plan.assumptions[k]=el.type==='month'?el.value:el.value===''?null:Number(el.value);if(plan.assumptions.sources?.[k]){plan.assumptions.sources={...plan.assumptions.sources};delete plan.assumptions.sources[k]}el.closest('.bp-field').classList.remove('from','start');el.closest('.bp-field').querySelector('small').textContent='Your number';update()})
 host.querySelectorAll('[data-p]').forEach(el=>el.oninput=el.onchange=()=>{plan[el.dataset.p]=el.value;dirty=true;bar()})
 host.oninput=e=>{const row=e.target.closest('.bp-row');if(row){const list=plan[row.dataset.list],i=+row.dataset.i,f=e.target.dataset.f;list[i][f]=f==='amount'?(e.target.value===''?null:Number(e.target.value)):e.target.value;dirty=true;const gap=C().fundingGap(plan),g=host.querySelector('.bp-gap');host.querySelectorAll('.bp-total')[0].textContent='Total '+usd(gap.uses);host.querySelectorAll('.bp-total')[1].textContent='Total '+usd(gap.sources);g.className='bp-gap '+(gap.gap>0?'short':gap.uses?'ok':'');g.textContent=!gap.uses?'Add your costs to see the funding picture.':gap.gap>0?'You’re '+usd(gap.gap)+' short of funding the plan.':gap.gap<0?'Funding exceeds costs by '+usd(-gap.gap)+'.':'Fully funded.';bar()}
  if(e.target.matches('[data-actual]')){plan.actuals={...(plan.actuals||{})};const v=e.target.value;if(v==='')delete plan.actuals[e.target.dataset.actual];else plan.actuals[e.target.dataset.actual]=Number(v);dirty=true;bar()}}
 host.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>{plan[b.dataset.add]=[...(plan[b.dataset.add]||[]),b.dataset.add==='uses'?{label:'',amount:null}:{label:'',amount:null,kind:'other'}];dirty=true;render();host.querySelector('[data-rows="'+b.dataset.add+'"] .bp-row:last-child input')?.focus()})
 host.onclick=e=>{if(e.target.matches('[data-remove]')){const row=e.target.closest('.bp-row');plan[row.dataset.list].splice(+row.dataset.i,1);dirty=true;render()}}
 host.querySelector('[data-summary]').onclick=()=>summaryView(plan)
 host.querySelector('[data-attach]').onclick=()=>connectExisting(plan.stage,plan)
 host.querySelector('[data-save]').onclick=async e=>{const btn=e.target,err=host.querySelector('.bp-err');err.textContent='';btn.disabled=true;btn.textContent='Saving…'
  try{const clean={...plan,uses:(plan.uses||[]).filter(u=>u.label),sources:(plan.sources||[]).filter(s=>s.label)};const out=await persist(clean,host.querySelector('[data-note]').value.trim());draft=null;dirty=false;metric('bizplan_saved',{stage:plan.stage,revisions:out.revisions.length});render()}catch(x){err.textContent=x.message;btn.disabled=false;btn.textContent='Save plan'}}}

/* ---------- connect an existing plan: upload, link, and keep its numbers alongside ---------- */
async function connectExisting(stage,plan){const d=dialog();d.innerHTML='<div class="bp-dialog-in"><button type="button" class="bp-close" aria-label="Close">×</button><h2>Connect your existing plan</h2><p>Add the business plan, projections or pitch deck you already have. It’s stored privately with '+E(loc.wallet.name)+' and linked here. Next, set the few numbers that drive your projections so Fran can track plan versus actual.</p><form class="bp-upload"><label class="bp-drop"><input type="file" multiple accept=".pdf,.xlsx,.xls,.csv,.docx,.doc,.pptx,.txt"><strong>Choose files</strong><small>PDF, spreadsheet, slides or document · up to 25 MB each</small><em data-files></em></label><label class="bp-consent"><input type="checkbox"> Store these privately with '+E(loc.wallet.name)+'. Nothing is shared.</label><p class="bp-err" role="alert"></p><button type="submit" class="bp-save" disabled>Attach</button></form></div>'
 if(!d.open)d.showModal();d.querySelector('.bp-close').onclick=()=>d.close()
 const f=d.querySelector('form'),input=f.querySelector('input[type=file]'),consent=f.querySelector('.bp-consent input'),go=f.querySelector('.bp-save'),sync=()=>{go.disabled=!(input.files.length&&consent.checked)}
 input.onchange=()=>{f.querySelector('[data-files]').textContent=[...input.files].map(x=>x.name).join(', ');sync()};consent.onchange=sync
 f.onsubmit=async e=>{e.preventDefault();go.disabled=true;go.textContent='Attaching…';const docs=[];try{for(const file of input.files){if(file.size>25*1024*1024)throw Error(file.name+' is over 25 MB.');const id=await window.FranDetails.uploadFile(file,'Other');docs.push({id,name:file.name,kind:/project|forecast|pro ?forma|\.xlsx?$|\.csv$/i.test(file.name)?'projections':/plan|pitch|deck/i.test(file.name)?'business_plan':'other'})}
  const base=plan||saved()||newPlan(stage);draft={...base,documents:[...(base.documents||[]),...docs]};dirty=true;d.close();metric('bizplan_started',{mode:'existing',files:docs.length});open()}catch(x){f.querySelector('.bp-err').textContent=x.message;go.disabled=false;go.textContent='Attach'}}}
function dialog(){let d=$('bp-dialog');if(d)return d;d=document.createElement('dialog');d.id='bp-dialog';d.className='bp-dialog';d.setAttribute('aria-label','Business plan');d.addEventListener('click',e=>{if(e.target===d)d.close()});document.body.append(d);return d}

/* ---------- lender summary: one printable page built from the Wallet ---------- */
function summaryHTML(plan){const p=C().project(plan.assumptions||{}),gap=C().fundingGap(plan),ent=entity()||{},lease=records('lease')[0]?.data,loans=records('loan').map(r=>r.data),owners=(ent.owners||[]).filter(o=>o?.name)
 return '<article class="bp-summary"><header><small>BUSINESS SUMMARY · '+E(new Date().toLocaleDateString('en-US',{month:'long',day:'numeric',year:'numeric'}))+'</small><h1>'+E(ent.name||loc.wallet.name)+'</h1><p>'+E([loc.wallet.name,loc.wallet.state,ent.entity_type,ent.ein?'EIN '+ent.ein:''].filter(Boolean).join(' · '))+'</p></header>'+
  (plan.summary?'<section><h2>Summary</h2><p>'+E(plan.summary)+'</p></section>':'')+(plan.concept||plan.market?'<section class="two"><div><h2>Concept</h2><p>'+E(plan.concept||'—')+'</p></div><div><h2>Market</h2><p>'+E(plan.market||'—')+'</p></div></section>':'')+
  '<section class="two"><div><h2>Ownership</h2><p>'+(owners.length?owners.map(o=>E(o.name)+(o.percentage!=null?' · '+o.percentage+'%':'')).join('<br>'):E(plan.team||'—'))+'</p></div><div><h2>Location</h2><p>'+(lease?E(lease.premises||loc.wallet.name)+'<br>Landlord: '+E(lease.landlord)+(lease.expiration_date?'<br>Lease through '+E(new Date(lease.expiration_date+'T12:00:00Z').toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric',timeZone:'UTC'})):'')+(lease.base_rent?'<br>Base rent '+usd(lease.base_rent)+(lease.base_rent_period==='year'?'/yr':'/mo'):''):'Lease not on file')+'</p></div></section>'+
  (gap.uses?'<section><h2>Sources & uses</h2><table class="su"><thead><tr><th>Uses</th><th></th><th>Sources</th><th></th></tr></thead><tbody>'+Array.from({length:Math.max(plan.uses.length,plan.sources.length)},(_,i)=>'<tr><td>'+E(plan.uses[i]?.label||'')+'</td><td>'+(plan.uses[i]?usd(plan.uses[i].amount):'')+'</td><td>'+E(plan.sources[i]?.label||'')+'</td><td>'+(plan.sources[i]?usd(plan.sources[i].amount):'')+'</td></tr>').join('')+'<tr class="sum"><td>Total</td><td>'+usd(gap.uses)+'</td><td>Total</td><td>'+usd(gap.sources)+'</td></tr></tbody></table>'+(gap.gap>0?'<p class="note">Funding gap: '+usd(gap.gap)+'</p>':'')+'</section>':'')+
  (p?'<section><h2>Projections</h2><table><thead><tr><th></th>'+p.years.map(y=>'<th>Year '+y.year+'</th>').join('')+'</tr></thead><tbody>'+[['Revenue','revenue'],['EBITDA','ebitda'],['Debt payments','debt'],['Cash after debt','cash'],['Cash taxes','taxes'],['Capital spending','capex'],['Working capital investment','workingCapital'],['Owner distributions','distributions'],['Net cash movement','cashMovement'],['Ending scenario cash','endingCash']].map(([l,k])=>'<tr><td>'+l+'</td>'+p.years.map(y=>'<td>'+usd(y[k])+'</td>').join('')+'</tr>').join('')+'<tr><td>DSCR</td>'+p.years.map(y=>'<td>'+(y.dscr===null?'—':y.dscr.toFixed(2)+'×')+'</td>').join('')+'</tr></tbody></table><p class="note">Projections are calculated from the owner’s assumptions'+(Object.keys(plan.assumptions?.sources||{}).length?'; some inputs come from records in this Wallet (lease, loan schedule, QuickBooks)':'')+'. They are estimates, not guarantees.'+(!(Number(plan.assumptions?.other_monthly)>0)?' Other operating costs were not entered.':'')+'</p></section>':'')+
  (loans.length?'<section><h2>Existing debt</h2><table><thead><tr><th>Lender</th><th>Amount</th><th>Rate</th><th>Term</th><th>Payment</th></tr></thead><tbody>'+loans.map(l=>{const s=X()?.schedule(l);return '<tr><td>'+E(l.lender)+'</td><td>'+usd(l.amount)+'</td><td>'+E(l.apr)+'%</td><td>'+E(l.term_months)+' mo</td><td>'+usd(s?.payment??l.payment,2)+'</td></tr>'}).join('')+'</tbody></table></section>':'')+
  '<footer>Prepared in Fran Wallet from owner-provided records. Verify against original documents.</footer></article>'}
function summaryView(plan){const d=dialog();d.innerHTML='<div class="bp-dialog-in wide"><button type="button" class="bp-close" aria-label="Close">×</button><div class="bp-summary-bar"><p>A one-page summary lenders recognize, built from this plan and your Wallet records.</p><button type="button" class="bp-save" data-print>Print or save as PDF</button></div>'+summaryHTML(plan)+'</div>';if(!d.open)d.showModal()
 d.querySelector('.bp-close').onclick=()=>d.close();d.querySelector('[data-print]').onclick=()=>{let root=$('bp-print-root');if(!root){root=document.createElement('div');root.id='bp-print-root';document.body.append(root)}root.innerHTML=summaryHTML(plan);document.body.classList.add('bp-printing');const done=()=>{document.body.classList.remove('bp-printing');root.innerHTML='';removeEventListener('afterprint',done)};addEventListener('afterprint',done);window.print();metric('bizplan_summary_printed',{})}}

/* ---------- compact start inside the journey ---------- */
function quickStart(host,{stage,documents=[]}){return new Promise(resolve=>{const base=structuredClone(saved()||newPlan(stage));if(documents.length)base.documents=[...(base.documents||[]),...documents.filter(d=>d.name&&!(base.documents||[]).some(x=>x.name===d.name))]
 const a=base.assumptions,loan=records('loan')[0]?.data,pre=stage==='preopening'
 host.innerHTML='<form class="bp-quick"><header><h3>'+(pre?'Your opening plan':'Your plan from here')+'</h3><p>'+(pre?'Five numbers. I’ll do the rest and keep it editable.':'Two numbers, plus what your Wallet already knows.')+'</p></header><div class="bp-grid2">'+
  (pre?'<label class="bp-field"><span>Opening month</span><input name="start_month" type="month" required value="'+E(a.start_month||'')+'"></label><label class="bp-field"><span>Total cost to open</span><div class="bp-in"><em>$</em><input name="cost" type="number" min="0" step="any" required placeholder="Build-out, equipment, fees, working capital"></div></label><label class="bp-field"><span>Your equity</span><div class="bp-in"><em>$</em><input name="equity" type="number" min="0" step="any"></div></label><label class="bp-field"><span>Loan amount</span><div class="bp-in"><em>$</em><input name="loan" type="number" min="0" step="any" value="'+E(loan?.amount??'')+'"></div>'+(loan?'<small>From your '+E(loan.lender)+' note</small>':'')+'</label><label class="bp-field"><span>Monthly sales once established</span><div class="bp-in"><em>$</em><input name="revenue_start" type="number" min="1" step="any" required value="'+E(a.revenue_start??'')+'"></div></label>'
   :'<label class="bp-field"><span>Monthly sales today</span><div class="bp-in"><em>$</em><input name="revenue_start" type="number" min="1" step="any" required value="'+E(a.revenue_start??'')+'"></div><small>'+E(a.sources?.revenue_start||'Your best estimate')+'</small></label><label class="bp-field"><span>Growth next year</span><div class="bp-in"><input name="growth_pct" type="number" step="0.5" value="'+E(a.growth_pct??3)+'"><em>%</em></div></label>')+
  '<label class="bp-field"><span>Other operating costs</span><div class="bp-in"><em>$</em><input name="other_monthly" type="number" min="0" step="any" value="'+E(a.other_monthly??'')+'" placeholder="Per month"></div><small>Utilities, software, repairs, insurance, fees</small></label></div><ul class="bp-knows">'+Object.entries(a.sources||{}).filter(([k,s])=>!/^Starting/.test(s)&&k!=='revenue_start').map(([k,s])=>'<li>✓ '+E({rent_monthly:'Occupancy '+usd(a.rent_monthly)+'/mo',debt_service_monthly:'Debt payments '+usd(a.debt_service_monthly)+'/mo',cogs_pct:'Cost of goods '+a.cogs_pct+'%',labor_pct:'Labor '+a.labor_pct+'%'}[k]||k)+' <small>'+E(s)+'</small></li>').join('')+'</ul><p class="bp-err" role="alert"></p><footer><button type="submit" class="bp-save">Build my plan</button><button type="button" class="bp-skipq" data-skip>Not now</button></footer></form>'
 const f=host.querySelector('form');f.querySelector('[data-skip]').onclick=()=>resolve(null)
 f.onsubmit=async e=>{e.preventDefault();if(!f.reportValidity())return;const v=Object.fromEntries(new FormData(f)),num=k=>v[k]===''||v[k]===undefined?null:Number(v[k]),btn=f.querySelector('.bp-save');btn.disabled=true;btn.textContent='Building…'
  const plan={...base,assumptions:{...a,revenue_start:num('revenue_start'),other_monthly:num('other_monthly'),...(pre?{start_month:v.start_month}:{growth_pct:num('growth_pct')})}}
  if(pre){plan.opening_date=v.start_month+'-01';const cost=num('cost');if(cost)plan.uses=[{label:'Total cost to open',amount:cost}];plan.sources=[...(num('equity')?[{label:'Owner equity',amount:num('equity'),kind:'equity'}]:[]),...(num('loan')?[{label:loan?(loan.loan_type||'Loan')+' · '+loan.lender:'Loan',amount:num('loan'),kind:'loan'}]:[])]
   if(num('loan')&&!a.debt_service_monthly){const s=X()?.schedule({amount:num('loan'),apr:loan?.apr||10,term_months:loan?.term_months||120});if(s){plan.assumptions.debt_service_monthly=s.payment;plan.assumptions.sources={...plan.assumptions.sources,debt_service_monthly:loan?'From your loan terms':'Estimated at 10% over 10 years: replace with your loan terms'}}}}
  try{const out=await persist(plan,'Started with Fran');draft=null;dirty=false;metric('bizplan_saved',{stage,quick:true});resolve(out)}catch(x){f.querySelector('.bp-err').textContent=x.message;btn.disabled=false;btn.textContent='Build my plan'}}
 requestAnimationFrame(()=>f.querySelector('input')?.focus({preventScroll:true}))})}
function brief(plan){const p=C().project(plan.assumptions||{}),gap=C().fundingGap(plan);if(!p)return '';const y=p.years[0]
 return '<div class="bp-brief"><div><span>Year 1 revenue</span><strong>'+short(y.revenue)+'</strong></div><div><span>Year 1 EBITDA</span><strong>'+short(y.ebitda)+'</strong></div><div><span>DSCR</span><strong>'+(y.dscr===null?'—':y.dscr.toFixed(2)+'×')+'</strong></div><div><span>'+(gap.uses?'Funding':'Break-even')+'</span><strong>'+(gap.uses?(gap.gap>0?short(gap.gap)+' short':'Funded'):(p.break_even?ym(p.break_even):'—'))+'</strong></div></div>'}
function open(){window.switchTab?.('bizplan')}
window.addEventListener('fran:location',e=>{if(e.detail?.wallet?.id!==loc?.wallet?.id){life=null;draft=null;dirty=false}loc=e.detail;navItem();render()})
window.addEventListener('fran:readiness',e=>{if(e.detail?.location?.wallet?.id!==loc?.wallet?.id)return;life=e.detail.life;if(!dirty)draft=null;render()})
window.FranBizPlan={open,quickStart,brief,summaryHTML,saved:()=>saved(),render}
})()
