/* Wallet-scoped conversation workspace. No cross-wallet aggregation or new entitlement. */
(()=>{'use strict';
const E=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const main=document.querySelector('#view-wallet .main'),nav=document.getElementById('release-nav');if(!main||!nav)return;
let state=null,mounted=null,activeSetupTopic=null;
let pendingWallet=null,setupTurnId=0;
function portfolioWallets(){return typeof ME!=='undefined'&&ME&&typeof WALLET_ID!=='undefined'&&WALLET_ID==='all'&&typeof WALLETS!=='undefined'?WALLETS.filter(w=>!w.access_role&&!w.team_role):[];}
function renderPortfolio(){mounted?.close();mounted=null;entry.hidden=false;page.innerHTML='<div class="ask-heading"><div><span class="ask-eyebrow">YOUR BUSINESS, IN CONVERSATION</span><h1>Which Wallet can I help with?</h1><p>Pick a location to ask about its records or take the next setup step.</p></div></div><section class="ask-wallet-picker" aria-label="Choose a Wallet"><label for="ask-wallet-search">Find a location</label><input id="ask-wallet-search" type="search" placeholder="Search your Wallets"><div class="ask-connection-results"></div><p role="status"></p></section><p class="ask-scope-note">Each conversation uses one Wallet’s records. Cross-location answers are not available here yet.</p>';const input=page.querySelector('input'),results=page.querySelector('.ask-connection-results'),status=page.querySelector('[role=status]');function filter(){const wallets=portfolioWallets().filter(w=>w.name.toLowerCase().includes(input.value.trim().toLowerCase()));results.innerHTML=wallets.map(w=>'<button type="button" data-chat-wallet="'+E(w.id)+'"><span>LOCATION WALLET</span><strong>'+E(w.name)+'</strong><p>Ask a question · Continue setup</p><small>Open this Wallet →</small></button>').join('');status.textContent=wallets.length?wallets.length+' Wallet'+(wallets.length===1?'':'s'):'No matching Wallets. Try another name.';results.querySelectorAll('button').forEach(b=>b.onclick=()=>{pendingWallet=b.dataset.chatWallet;window.setActiveWallet(pendingWallet);launch();});}input.oninput=filter;filter();}
let reviewed=new Set();
let savedReviewContext=null;
function savedReviews(){if(savedReviewContext?.location?.wallet?.id!==state?.wallet?.id)return [];const ids=new Set((state?.records||[]).filter(r=>r.kind==='document').map(r=>r.id));return (savedReviewContext.items||[]).filter(item=>item.status==='current'&&item.evidence?.status==='attached'&&item.evidence.confirmed_at&&item.evidence.document_ids?.length&&item.evidence.document_ids.every(id=>ids.has(id)));}
function openSavedReviews(){window.switchTab?.('readiness');const first=savedReviews()[0];if(first)dispatchEvent(new CustomEvent('fran:open-evidence',{detail:{id:first.id}}));}
window.addEventListener('fran:activation-context',e=>{savedReviewContext=e.detail;milestonePanel()});
function openNextPriorities(){window.switchTab?.('dashboard');requestAnimationFrame(()=>{const target=document.querySelector('#page-dashboard .wallet-priorities h2')||document.querySelector('#page-dashboard h1');if(target){target.setAttribute('tabindex','-1');target.focus({preventScroll:true});target.scrollIntoView({block:'center',behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'});}});}
function milestonePanel(){const host=page.querySelector('.ask-sources');if(!host||!state?.wallet)return;let box=host.querySelector('.ask-milestones');if(!box){box=document.createElement('section');box.className='ask-milestones';host.prepend(box)}const catalog=window.FRAN_SETUP_JOURNEY?.catalog()||[],saved=catalog.filter(t=>t.saved),confirmed=saved.filter(t=>reviewed.has(t.id)),durable=savedReviews();box.innerHTML='<h2>Your first useful result</h2><ol><li>'+ (window.FRAN_SETUP_ACTIONS?.profile?.()?'✓':'○')+' Choose your outcome</li><li>'+(saved.length?'✓':'○')+' Save a source</li><li>'+(confirmed.length||durable.length?'✓':'○')+' Review its dates & coverage</li></ol><p>'+E(durable.length?'A current owner-confirmed review is saved in your plan. This is not independent verification.':confirmed.length?'You confirmed a source review this visit. This is not an independent verification.':saved.length?'A source is saved. Open it and check what it covers.':'One useful source is enough to begin.')+'</p>';if(saved.length){const b=document.createElement('button');b.type='button';b.className='ask-library';b.textContent=durable.length?'Open saved evidence review':'Save dates & coverage in my plan';b.onclick=openSavedReviews;box.append(b)}if(durable.length){const next=document.createElement('button');next.type='button';next.className='ask-library';next.textContent='Review my next priorities';next.onclick=openNextPriorities;box.append(next)}}
function reviewStep(topic){setupMessage('Open '+topic.name.toLowerCase()+' and check the reporting period, source date, and any missing information. When you return, confirm what you reviewed.',[['Open the source',()=>window.FRAN_SETUP_JOURNEY.review(topic.id)],['I checked the dates and coverage',()=>{const saved=window.FRAN_SETUP_JOURNEY.catalog().find(t=>t.id===topic.id)?.saved;if(!saved)return setupMessage('That source is no longer saved in this Wallet. Add or reconnect it before marking it reviewed.',[['Return to setup',()=>setupStep(topic.id)]]);reviewed.add(topic.id);window.FRAN_SETUP_JOURNEY.clearResume?.();milestonePanel();try{window.posthog?.capture('wallet_source_review_confirmed',{topic:topic.id})}catch(_){}setupMessage('Review noted for this visit. You can now ask a question about that source or choose another useful step. This does not verify that the information is complete or correct.',[['Choose my next step',()=>setupStep()],['Explore another area',setupLibrary]])}],['Something is missing',()=>setupStep(topic.id)]]);}
const page=document.createElement('section');page.id='page-ask';page.className='page';main.append(page);
const entry=document.createElement('button');entry.type='button';entry.className='nav-item release-nav';entry.dataset.page='ask';entry.textContent='Ask your Wallet';entry.hidden=true;nav.prepend(entry);
function launch(){if(!state?.wallet){if(portfolioWallets().length){renderPortfolio();window.switchTab('ask');}else if(typeof ME!=='undefined'&&ME&&typeof WALLET_ID!=='undefined'&&WALLET_ID&&WALLET_ID!=='all'){pendingWallet=WALLET_ID;entry.hidden=false;page.innerHTML='<div class="ask-heading"><div><h1>Opening your Wallet…</h1><p role="status">Loading this location’s records and setup progress.</p><button type="button" class="ask-library" data-ask-retry>Retry loading</button></div></div>';page.querySelector('[data-ask-retry]').onclick=()=>window.refreshLocation?.(true);window.switchTab('ask');}return;}if(state.wallet.access_role)return;window.switchTab('ask');if(mounted&&!mounted.isConnected){const other=document.getElementById("wallet-dialog");other?.close();other?.remove();page.querySelector(".ask-conversation").append(mounted);if(!mounted.open)mounted.show();}if(!mounted){const host=page.querySelector('.ask-conversation');mounted=window.mountFranAIConversation?.(host);if(!mounted)host.textContent='The conversation could not load. Refresh this page to try again; your saved records are unchanged.';}enhanceWorkspace();page.querySelector('#wallet-ai-question')?.focus({preventScroll:true});}
entry.onclick=launch;
matchMedia('(max-width:600px)').addEventListener('change',e=>{const drawer=page.querySelector('.ask-source-drawer');if(drawer)drawer.open=!e.matches;const history=page.querySelector('#wallet-ai-history'),last=history?.lastElementChild;if(last)requestAnimationFrame(()=>history.scrollTo({top:history.scrollTop+last.getBoundingClientRect().top-history.getBoundingClientRect().top,behavior:'auto'}))});
function enhanceWorkspace(){const list=page.querySelector('.ask-source-list');if(list&&!list.closest('.ask-source-drawer')){const details=document.createElement('details');details.className='ask-source-drawer';details.open=!matchMedia('(max-width:600px)').matches;const summary=document.createElement('summary');summary.textContent='View connected and missing sources';list.before(details);details.append(summary,list)}const history=page.querySelector('#wallet-ai-history');if(history){history.setAttribute('role','log');history.setAttribute('aria-label','Wallet conversation');history.setAttribute('tabindex','0')}const input=page.querySelector('#wallet-ai-question');if(input)input.placeholder='Ask about your Wallet, or type /setup';}
function chooseOutcome(nextTopic){const wallet=state?.wallet?.id;const choices=[['maintain','Run this location with more clarity'],['financing','Prepare for financing'],['exit','Prepare for a future sale'],['both','Stay ready for financing and a sale'],['services','Find a service or provider']];setupMessage('Choose one direction. You can change it later; you do not need every account connected.',choices.map(([goal,label])=>[label,async button=>{const api=window.FRAN_SETUP_ACTIONS;if(!api?.chooseGoal)return api?.goalGuide();button.closest('.ask-inline-actions').querySelectorAll('button').forEach(b=>b.disabled=true);let saved=false;try{saved=await api.chooseGoal(goal==='services'?'maintain':goal,button)}catch(_){}if(state?.wallet?.id!==wallet)return;if(!saved)return setupMessage('That choice could not be saved. Your records are unchanged. Try again when your connection is ready.',[['Try again',()=>chooseOutcome(nextTopic)]]);milestonePanel();goal==='services'?setupLibrary():setupStep(nextTopic)}]),'What would make Fran useful first?');}
function setupMessage(text,actions=[],heading=''){document.getElementById("fran-connectors")?.close();launch();const history=page.querySelector('#wallet-ai-history');if(!history)return;history.querySelectorAll('.ask-setup-turn button').forEach(b=>b.disabled=true);const item=document.createElement('article');item.className='ask-setup-turn'+(heading?' ask-outcome-turn':'');item.innerHTML='<small>FRAN · SETUP GUIDE</small>'+(heading?'<h3>'+E(heading)+'</h3>':'')+'<p>'+E(text)+'</p><div class="ask-inline-actions"></div>';const descriptionId='ask-setup-context-'+(++setupTurnId);const description=item.querySelector('p');description.id=descriptionId;const title=item.querySelector('h3');if(title)title.id=descriptionId+'-title';const group=item.querySelector('div');actions.forEach(([label,action])=>{const b=document.createElement('button');b.type='button';b.textContent=label;b.setAttribute('aria-describedby',(title?title.id+' ':'')+descriptionId);b.onclick=()=>{const response=document.createElement('p');response.className='ask-your-choice';response.textContent='You · '+label;item.append(response);action(b)};group.append(b)});history.append(item);item.scrollIntoView({block:'nearest',behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'});group.querySelector('button')?.focus({preventScroll:true});requestAnimationFrame(()=>{if(item.isConnected)history.scrollTo({top:history.scrollTop+item.getBoundingClientRect().top-history.getBoundingClientRect().top,behavior:'auto'})});}
function setupStep(id){const journey=window.FRAN_SETUP_JOURNEY;if(!journey)return window.openFranSetup?.();const api=window.FRAN_SETUP_ACTIONS;const catalog=journey.catalog();if(api?.profile&&!api.profile()&&!catalog.some(t=>t.id===id&&t.saved))return chooseOutcome(id);const topic=catalog.find(t=>t.id===(id||journey.resume?.()||journey.next()));if(!topic){setupMessage('You can stop here or revisit an area. Skipped steps are not connected, and saved sources still need their dates and coverage checked.',[['Choose an area',setupLibrary]]);return;}
 activeSetupTopic=topic.id;
 const health=window.FRAN_SETUP_ACTIONS?.connectorHealth?.(topic.id);
 setupMessage(topic.question+' '+topic.copy+(health&&health.state!=='current'?' '+health.label+'. '+(health.note||''):''),[
 [topic.saved?'Review my saved source':topic.choices[0],()=>{if(topic.saved)return reviewStep(topic);setupMessage(topic.saved?'Open the source and check its reporting period and coverage. Come back here when you are ready for another step.':'I’ll open the connection or import options. Nothing is connected until the source is successfully saved.',[['Continue setup',()=>setupStep()],['Choose another area',setupLibrary]]);topic.saved?journey.review(topic.id):journey.connect(topic.id)}],
 [topic.choices[1],()=>setupMessage('I can prepare a request for the CoverPanda team. You will review the message and consent before sending. Availability, fees and any eligible offer must be confirmed; no service starts here.',[['Prepare my request',()=>journey.draft(topic.id)],['Explore apps & offers',()=>journey.market(topic.id)],['Back to this step',()=>setupStep(topic.id)]])],
 ['Add a file instead',()=>{setupMessage('Add an original you already have. After saving, review what Fran could read and what still needs confirmation.',[['Continue setup',()=>setupStep(topic.id)]]);addSetupFile()}],
 ['Why this step?',()=>setupMessage('This helps build '+topic.value.toLowerCase()+'. You can use the service you already have; connecting every area is not required.',[['Continue',()=>setupStep(topic.id)],['Choose another area',setupLibrary]])],
 ['Not now',()=>{journey.skip(topic.id);setupStep()}]
 ]);
}
function setupLibrary(){const catalog=window.FRAN_SETUP_JOURNEY?.catalog();if(!catalog)return window.openFranSetupPlan?.();setupMessage('Choose what you want to understand. Use a connection, add a file, or find help getting started.');const turn=page.querySelector('.ask-setup-turn:last-child'),library=document.createElement('div');library.className='ask-connection-library';library.innerHTML='<label>Find a connection or business area<input type="search" placeholder="Try banking, insurance, or legal" aria-label="Search setup areas"></label><div class="ask-connection-results"></div><p role="status" class="ask-library-count"></p>';turn.append(library);const draw=()=>{const query=library.querySelector('input').value.trim().toLowerCase(),matches=catalog.filter(t=>[t.name,t.question,t.copy,...(t.preview||[])].join(' ').toLowerCase().includes(query));library.querySelector('.ask-connection-results').innerHTML=matches.map(t=>{const health=window.FRAN_SETUP_ACTIONS?.connectorHealth?.(t.id);return '<button type="button" data-library-topic="'+E(t.id)+'"><span>'+E(health?.label||(t.saved?'Source saved':'Start here'))+'</span><strong>'+E(t.name)+'</strong><p>'+E(t.value)+'</p><small>'+E(t.copy)+'</small></button>'}).join('');library.querySelector('.ask-library-count').textContent=matches.length?matches.length+' areas available':'No matching area. Try another term or browse all areas.';library.querySelectorAll('[data-library-topic]').forEach(b=>b.onclick=()=>setupStep(b.dataset.libraryTopic))};library.querySelector('input').oninput=draw;draw();library.querySelector('input').focus({preventScroll:true});}
// Setup commands are free and local. Other questions retain the existing AI flow.
function addSetupFile(){activeSetupTopic='document';window.FRAN_SETUP_JOURNEY?.addFile?window.FRAN_SETUP_JOURNEY.addFile():window.FRAN_SETUP_JOURNEY?.connect('document')}
function setupHelp(intent){const journey=window.FRAN_SETUP_JOURNEY,topic=journey?.catalog().find(t=>t.id===activeSetupTopic);if(!topic)return setupStep();if(intent==='done'){if(topic.saved)return reviewStep(topic);return setupMessage('I don’t see a saved '+topic.name.toLowerCase()+' source yet. Opening a connection or choosing a file does not finish saving it. You can retry, use a file, or return later.',[['Try this step again',()=>setupStep(topic.id)],['Add a file',()=>addSetupFile()],['Choose another area',setupLibrary]])}if(intent==='next')return topic.saved&&!reviewed.has(topic.id)?reviewStep(topic):setupStep();setupMessage(intent==='explain'?'For this step, '+topic.copy+' The useful result is '+topic.value.toLowerCase()+'. Choose the option that matches what you already have.':'Let’s get you unstuck. You can retry this step, use a document instead of a connection, or look for help. Nothing will be submitted automatically.',[['Show my options',()=>setupStep(topic.id)],['Use a file instead',()=>addSetupFile()],['Choose another area',setupLibrary]]);}
page.addEventListener('submit',e=>{if(e.target.id!=='wallet-ai-form')return;const q=e.target.elements.question.value.trim(),setup=/^\/(setup|connect)\b/i.test(q)||/^(help me (set up|setup|get started)( my wallet)?|set up my wallet|show connections)[.!?]?$/i.test(q),intent=activeSetupTopic?(/^(done|consider it done|i('ve| have) finished)[.!?]?$/i.test(q)?'done':/^(what('s| is) next|next)[.!?]?$/i.test(q)?'next':/^(explain( this step)?|why this step)[.!?]?$/i.test(q)?'explain':/^(i['’]?m stuck|i am stuck|i (could not|couldn't|can’t|can't) complete this step)[.!?]?$/i.test(q)?'stuck':null):null;if(!setup&&!intent)return;e.preventDefault();e.stopImmediatePropagation();e.target.reset();const previous=page.querySelector('.ask-setup-turn:last-child');if(previous){const note=document.createElement('p');note.className='ask-your-choice';note.textContent='You · '+q;previous.append(note)}if(intent)return setupHelp(intent);/^\/connect\b|^show connections/i.test(q)?setupLibrary():setupStep();},true);
function sources(){const catalog=window.FRAN_SETUP_JOURNEY?.catalog()||[];return catalog.map(t=>{const health=window.FRAN_SETUP_ACTIONS?.connectorHealth?.(t.id),label=health?.label||(t.saved?'Source saved · review coverage':'No saved source yet');return '<article><div><strong>'+E(t.name)+'</strong><small>'+E(label)+'</small></div><button type="button" data-source="'+E(t.id)+'" data-destination="'+E(t.route||'documents')+'" data-saved="'+t.saved+'">'+(t.saved?'Review':'Add')+'</button></article>'}).join('')}
function render(){if(!state?.wallet&&portfolioWallets().length){renderPortfolio();return;}entry.hidden=!state?.wallet||!!state?.wallet?.access_role;if(entry.hidden){mounted?.close();mounted=null;page.replaceChildren();return;}page.innerHTML='<div class="ask-heading"><div><span class="ask-eyebrow">YOUR BUSINESS, IN CONVERSATION</span><h1>Ask your Wallet.</h1><p>Understand what you have. Find your next useful step.</p></div><span class="ask-scope">'+E(state.wallet.name)+'<small>Only this Wallet</small></span></div><div class="ask-layout"><div><section class="ask-start"><h2>Where would you like to start?</h2><div><button data-ask-setup>Help me set up my Wallet <span>Start with one useful source →</span></button><button data-ask-question="Give me an overview of my business">Understand my business <span>Ask about saved records →</span></button></div></section><section class="ask-conversation" aria-label="Wallet conversation"></section></div><aside class="ask-sources"><h2>Your sources</h2><p>Answers depend on what is saved here. A source on file may still be incomplete or out of date.</p><div class="ask-source-list">'+sources()+'</div><button class="ask-library" data-ask-library>Explore connections & setup →</button><details><summary>How your answers work</summary><p>Fran searches records for this Wallet. Check citations and reporting dates before acting. Setup help is available without a paid AI plan; generated answers use your plan’s allowance.</p><p>Save a private chat to return to it later. Unsaved conversation text clears when you switch Wallets or refresh. Saved answers are snapshots, not refreshed financial results.</p></details></aside></div>';mounted=null;
 page.querySelector('[data-ask-setup]').onclick=()=>setupStep();page.querySelector('[data-ask-library]').onclick=setupLibrary;page.querySelector('[data-ask-question]').onclick=e=>{launch();const f=page.querySelector('#wallet-ai-form');if(f){f.elements.question.value=e.currentTarget.dataset.askQuestion;f.requestSubmit();}};
 page.querySelectorAll('[data-source]').forEach(b=>b.onclick=()=>{setupStep(b.dataset.source)});
}
window.addEventListener('fran:location',e=>{const changed=state?.wallet?.id!==e.detail?.wallet?.id||state?.wallet?.access_role!==e.detail?.wallet?.access_role;state=e.detail;if(changed)activeSetupTopic=null;if(changed||!page.children.length)render();else{const list=page.querySelector('.ask-source-list');if(list){list.innerHTML=sources();list.querySelectorAll('[data-source]').forEach(b=>b.onclick=()=>setupStep(b.dataset.source))}}});
window.openFranAskWorkspace=launch;
window.addEventListener('fran:location',e=>{if(!pendingWallet||!e.detail?.wallet)return;const id=pendingWallet;pendingWallet=null;if(e.detail.wallet.id===id&&!e.detail.wallet.access_role)launch();});
window.addEventListener('fran:conversation-restored',()=>{activeSetupTopic=null;});
let reviewVersion='';
let companyVersion='';
window.addEventListener('fran:readiness',e=>{if(e.detail?.location?.wallet?.id!==state?.wallet?.id)return;const version=JSON.stringify([state?.wallet?.id,(e.detail.life?.records||[]).filter(r=>r.kind==='entity')]);if(version!==companyVersion){reviewed.delete('company');companyVersion=version}});
window.addEventListener('fran:location',()=>{const version=JSON.stringify([state?.wallet?.id,state?.records,state?.banks,state?.books]);if(version!==reviewVersion){reviewed.clear();reviewVersion=version}milestonePanel()});
window.addEventListener('fran:readiness',e=>{if(e.detail?.location?.wallet?.id!==state?.wallet?.id)return;queueMicrotask(()=>{milestonePanel();const list=page.querySelector('.ask-source-list');if(list){list.innerHTML=sources();list.querySelectorAll('[data-source]').forEach(b=>b.onclick=()=>setupStep(b.dataset.source))}})});
window.addEventListener('fran:health',e=>{if(e.detail?.wallet?.id!==state?.wallet?.id)return;page.querySelectorAll('[data-source]').forEach(b=>{const h=window.FRAN_SETUP_ACTIONS?.connectorHealth?.(b.dataset.source);if(h)b.closest('article').querySelector('small').textContent=h.label})});
if(window.FRAN_SETUP_JOURNEY)window.openFranSetup=()=>setupStep();
})();
