/* Public product tour. Screenshots contain synthetic sample data only. */
(()=>{
const $=s=>document.querySelector(s),shot=(file,alt)=>`<figure class="product-shot"><img src="${file}" alt="${alt}" loading="lazy" width="1280" height="900"><figcaption>${file.includes("books")?"Understand the month behind the numbers":file.includes("debt")?"Every obligation, in context":"Your location, at a glance"}<span title="This preview uses illustrative figures, not customer information."> · Preview</span></figcaption></figure>`;
const hero=$('.wallet-command-visual');if(hero)hero.outerHTML=shot('fran-product-wallet.png','Fran Wallet dashboard: location cash, profit, debt, insurance, records and next actions');
const sub=$('.hero-copy .land-sub');if(sub)sub.textContent='Banking, books, payroll, debt, insurance and business records—organized by location, with help when you need it.';
const promise=$('.hero-promise');if(promise)promise.textContent='See your cash, understand your profit, and know what needs attention.';
const demo=$('.hero-copy .land-cta-secondary');if(demo){demo.textContent='See how your Wallet works ↓';demo.onclick=()=>$('#land-howitworks').scrollIntoView({behavior:'smooth'})}
const brief=$('#land-outcome');if(brief){brief.innerHTML='<span class="ls-eyebrow">A wallet for your business</span><h2 class="ls-h2">The money. The records.<br>The next step.</h2><p class="ls-sub">Each location gets its own workspace. Connect the accounts you use, keep the original documents, and bring a clear question to the people who help you run it.</p>';brief.classList.remove('outcome-section');}
$('#land-who')?.remove();
const wallet=$('#land-wallet');if(wallet){wallet.querySelector('.ls-eyebrow').textContent='One home for every part of the business';wallet.querySelector('.land-quadrants').outerHTML='<div class="wallet-capabilities">'+[['Banking','Know your available cash and review activity.'],['Books','Understand revenue, expenses and profit.'],['Payroll','See labor costs and imported pay reports.'],['Debt','Keep loan balances, terms and statements together.'],['Insurance','Find policies, coverage records and renewal dates.'],['Documents','Keep the originals behind your business records.'],['Support & services','Find bookkeeping, payroll, insurance and formation help.']].map(([h,c])=>`<article><h3>${h}</h3><p>${c}</p></article>`).join('')+'</div>';}
const journey=$('.land-journey');if(journey)journey.outerHTML=`<div class="product-journey">
<article><div><small>01 · YOUR LOCATION</small><h3>Give the location a home.</h3><p>A private workspace for this store’s money, records and people. Use a nickname you recognize; add its legal entity later.</p></div><div class="journey-ui"><span class="agent-avatar">F.</span><strong>What would you like to name this wallet?</strong><div class="sample-field">Pine Street · Austin</div><small>Your store name or nickname. You can change it anytime.</small></div></article>
<article><div><small>02 · YOUR FIRST SOURCE</small><h3>Start with what you have.</h3><p>Connect an account or add a file. Fran explains what each source will help you see.</p></div><div class="journey-ui"><strong>What’s easiest to add today?</strong><div class="sample-options"><span>QuickBooks <small>Revenue & profit</small></span><span>Bank account <small>Cash & activity</small></span><span>A document <small>Lease, loan or policy</small></span></div><small>Setup preview · choose your own source inside Fran</small></div></article>
<article><div><small>03 · YOUR FIRST ANSWER</small><h3>See the picture take shape.</h3><p>Open your saved reports, review source dates, and see which details still need attention.</p></div>${shot('fran-product-books.png','Actual Fran Accounting view with revenue, profit and reporting-month controls')}</article>
<article><div><small>04 · YOUR NEXT MOVE</small><h3>Move the next thing forward.</h3><p>Review a result, gather a missing record, or ask your team for help. Choose the next step that serves your goal.</p></div><div class="journey-ui"><strong>Your first source is ready to explore</strong><p>QuickBooks · Review the reporting period and the accounts behind the result.</p><a href="wallet.html" class="sample-action">Open your Wallet →</a><small>Your accounting, payroll and insurance team are within reach.</small></div></article></div>`;
const debt=$('.debt-visual-wrap');if(debt)debt.outerHTML=shot('fran-product-debt.png','Actual Fran debt schedule: lender, recorded balance and date, payment, rate and monthly payment review');
const benefits=$('.debt-benefits');if(benefits)benefits.innerHTML='<li>Balances and terms by location</li><li>Statements beside the numbers</li><li>Payment matches for your review</li>';
const proof=$('#land-proof');if(proof){proof.classList.add('product-proof');proof.innerHTML=`<div><span class="ls-eyebrow">Your numbers, with context</span><h2 class="ls-h2">Connect your books.<br>Understand your profit.</h2><p class="ls-sub">See revenue and costs by month. Open the details behind the result. Bring a focused question to your accountant.</p><a href="wallet.html" class="sample-action">Start with QuickBooks →</a></div>${shot('fran-product-books.png','Actual Fran Accounting dashboard showing monthly financial results')}`;}
const room=$('#land-value-room .land-quadrants');if(room)room.outerHTML=`<div class="room-preview"><div><small>PREPARED BY YOU · SAMPLE ROOM</small><h3>Pine Street · Financing room</h3><p>Choose the records for this conversation. Review the originals, then decide who can see them.</p><ul><li>Financial statements <span>Review reporting period</span></li><li>Loan statement <span>Check current balance</span></li><li>Lease & franchise agreement <span>Keep originals attached</span></li><li>Insurance policies <span>Review terms and expiry</span></li></ul></div><aside><h3>Your sharing controls</h3><p>Choose files and recipients.</p><p>Set an expiry date.</p><p>Revoke the link when needed.</p><small>Pro sharing · No records are shared from this preview.</small></aside></div>`;
const sign=$('.signin-next');if(sign){sign.querySelector('h2').textContent='A home for the business you’re building.';sign.querySelector('p').textContent='One location. Its money, records and next steps. Start with what you have and build from there.';sign.querySelector('ol').outerHTML=shot('fran-product-wallet.png','Preview of your location’s Wallet with cash, profit, debt and insurance');}
// Keep previews visibly distinct from the signed-in product, but readable on small screens.
document.querySelectorAll('.product-shot').forEach(figure=>{const img=figure.querySelector('img');if(!img)return;const button=document.createElement('button');button.type='button';button.className='product-preview-open';button.setAttribute('aria-label','Explore this product preview');img.before(button);button.append(img);const hint=document.createElement('span');hint.textContent='Explore this view ↗';button.append(hint);button.onclick=()=>openPreview(img,button);});
function openPreview(source,opener){let dialog=document.getElementById('fran-product-preview');if(!dialog){dialog=document.createElement('dialog');dialog.id='fran-product-preview';dialog.setAttribute('aria-labelledby','fran-preview-title');dialog.innerHTML='<header><div><h2 id="fran-preview-title">A closer look at your Wallet</h2><p>Illustrative figures. Your Wallet starts with your own records.</p></div><button type="button" aria-label="Close product preview">Close ×</button></header><div class="product-preview-scroll" tabindex="0" role="region" aria-label="Product screenshot; scroll horizontally to explore"><img alt=""></div><footer><span>On a small screen, swipe across the view to explore.</span><a href="wallet.html">Start your Wallet →</a></footer>';document.body.append(dialog);dialog.addEventListener('keydown',e=>{if(e.key!=='Tab')return;const items=[...dialog.querySelectorAll('button,a[href],[tabindex="0"]')],first=items[0],last=items.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}});dialog.querySelector('button').onclick=()=>dialog.close();dialog.addEventListener('click',e=>{if(e.target===dialog)dialog.close()});}const img=dialog.querySelector('img');img.src=source.src;img.alt=source.alt;dialog.onclose=()=>opener?.focus({preventScroll:true});dialog.showModal();dialog.querySelector('button').focus();requestAnimationFrame(()=>{dialog.querySelector('.product-preview-scroll').scrollLeft=innerWidth<600?Math.round(img.clientWidth*.18):0;});}
})();
