(()=>{'use strict';
// A second recipient link opened in this tab must replace the prior in-memory access key.
window.addEventListener('hashchange',()=>{if(location.hash)location.reload();});
const token=location.hash.slice(1);history.replaceState(null,'',location.pathname);const endpoint='https://nlshvthmcnwuygaeague.supabase.co/functions/v1/location';
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n);
async function call(action,extra={}){const r=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,token,...extra})});if(!r.ok){const d=await r.json().catch(()=>({}));throw Error(d.error||'Room unavailable.');}return r;}
if(!/^[a-f0-9]{64}$/.test(token)){document.getElementById('room-status').textContent='Open the original shared link to access this room. For privacy, its access key is not kept in browser history.';document.getElementById('open-room').disabled=true;}
document.getElementById('open-room').onclick=async e=>{e.target.disabled=true;document.getElementById('room-status').textContent='Opening…';try{const r=await(await call('view_room')).json();const p=r.payload,v=p.valuation,result=v?.result;document.getElementById('room').innerHTML=`<section class="fw-shell"><div class="fw-kicker">Snapshot created ${esc(r.created_at.slice(0,10))} · Access expires ${esc(r.expires_at.slice(0,10))}</div><h1>${esc(r.title)}</h1><p>${esc(p.location)}${p.brand?' · '+esc(p.brand):''}</p><p class="fw-note">${esc(p.notice)}</p>${v?`<hr><h2>Owner’s value scenario</h2>${result?.available?`<p class="fw-value">${money(result.low)} – ${money(result.high)}</p><p>Business value: ${money(result.earnings)} adjusted EBITDA × ${v.inputs.low}–${v.inputs.high}×.</p><p>Equity range: ${money(result.equityLow)} – ${money(result.equityHigh)}. Includes ${money(v.inputs.cash)} excess cash and subtracts ${money(result.debt)} reported debt.</p>`:'<p>Non-positive earnings; no earnings-multiple range calculated.</p>'}<p>Trailing 12 months ending ${esc(v.inputs.period_end)}. Multiple source: ${esc(v.inputs.basis)}.</p><p>Net income ${money(v.inputs.net)} + interest ${money(v.inputs.interest)} + income tax ${money(v.inputs.tax)} + depreciation/amortization ${money(v.inputs.da)} + adjustments ${money(v.inputs.adjustments)}.</p><p>${esc(v.inputs.notes)}</p>`:''}${p.debts?.length?`<hr><h2>Reported debt schedule</h2><div class="fw-table"><table><thead><tr><th>Lender / reference</th><th>Principal balance</th><th>Monthly payment</th><th>APR</th><th>As of</th></tr></thead><tbody>${p.debts.map(d=>`<tr><td>${esc(d.lender)}<small>${esc(d.reference)}</small></td><td>${money(d.balance)}</td><td>${money(d.payment)}</td><td>${d.apr}%</td><td>${esc(d.as_of)}</td></tr>`).join('')}</tbody></table></div>`:''}<hr><h2>Selected documents</h2>${r.documents.length?`<ul class="fw-file-list">${r.documents.map(d=>`<li><div class="fw-step-copy"><b>${esc(d.name)}</b><small>${esc(d.category)}</small></div><button class="btn" data-id="${esc(d.id)}">Download</button></li>`).join('')}</ul>`:'<p>The owner included financial summaries only.</p>'}<p id="download-status" role="status"></p></section>`;document.querySelectorAll('[data-id]').forEach(b=>b.onclick=async()=>{b.disabled=true;try{const d=r.documents.find(d=>d.id===b.dataset.id),res=await call('room_document',{id:d.id});const url=URL.createObjectURL(await res.blob()),a=document.createElement('a');a.href=url;a.download=d.name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(err){document.getElementById('download-status').textContent=err.message;}finally{b.disabled=false;}});}catch(err){document.getElementById('room-status').textContent=err.message;e.target.disabled=false;}};
})();
